/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthControllerLoginV1200,
  AuthControllerLogoutV1200,
  AuthControllerMeV1200,
  AuthControllerRefreshV1200,
  LoginRequest,
  LogoutRequest,
  RefreshRequest
} from '../../model';

import { axios } from '../../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 서비스 사용자 로그인 (Refresh Token + 초단기 JWT 발급)
 */
export const authControllerLoginV1 = (
    loginRequest: LoginRequest,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerLoginV1200>(
      {url: `/api/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      options);
    }




export const getAuthControllerLoginV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginV1>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginV1>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['authControllerLoginV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLoginV1>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerLoginV1(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLoginV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLoginV1>>>
    export type AuthControllerLoginV1MutationBody = LoginRequest
    export type AuthControllerLoginV1MutationError = unknown

    /**
 * @summary 서비스 사용자 로그인 (Refresh Token + 초단기 JWT 발급)
 */
export const useAuthControllerLoginV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginV1>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLoginV1>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {
      return useMutation(getAuthControllerLoginV1MutationOptions(options), queryClient);
    }
    /**
 * @summary Refresh Token 기반 초단기 AccessToken 갱신 및 토큰 회전
 */
export const authControllerRefreshV1 = (
    refreshRequest: RefreshRequest,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerRefreshV1200>(
      {url: `/api/v1/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshRequest, signal
    },
      options);
    }




export const getAuthControllerRefreshV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRefreshV1>>, TError,{data: RefreshRequest}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerRefreshV1>>, TError,{data: RefreshRequest}, TContext> => {

const mutationKey = ['authControllerRefreshV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRefreshV1>>, {data: RefreshRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerRefreshV1(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerRefreshV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRefreshV1>>>
    export type AuthControllerRefreshV1MutationBody = RefreshRequest
    export type AuthControllerRefreshV1MutationError = unknown

    /**
 * @summary Refresh Token 기반 초단기 AccessToken 갱신 및 토큰 회전
 */
export const useAuthControllerRefreshV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRefreshV1>>, TError,{data: RefreshRequest}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerRefreshV1>>,
        TError,
        {data: RefreshRequest},
        TContext
      > => {
      return useMutation(getAuthControllerRefreshV1MutationOptions(options), queryClient);
    }
    /**
 * @summary 로그아웃 (Refresh Token 무효화)
 */
export const authControllerLogoutV1 = (
    logoutRequest: LogoutRequest,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerLogoutV1200>(
      {url: `/api/v1/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: logoutRequest, signal
    },
      options);
    }




export const getAuthControllerLogoutV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogoutV1>>, TError,{data: LogoutRequest}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogoutV1>>, TError,{data: LogoutRequest}, TContext> => {

const mutationKey = ['authControllerLogoutV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogoutV1>>, {data: LogoutRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerLogoutV1(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLogoutV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogoutV1>>>
    export type AuthControllerLogoutV1MutationBody = LogoutRequest
    export type AuthControllerLogoutV1MutationError = unknown

    /**
 * @summary 로그아웃 (Refresh Token 무효화)
 */
export const useAuthControllerLogoutV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogoutV1>>, TError,{data: LogoutRequest}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogoutV1>>,
        TError,
        {data: LogoutRequest},
        TContext
      > => {
      return useMutation(getAuthControllerLogoutV1MutationOptions(options), queryClient);
    }
    /**
 * @summary 현재 로그인한 사용자 프로필 정보 조회
 */
export const authControllerMeV1 = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerMeV1200>(
      {url: `/api/v1/auth/me`, method: 'GET', signal
    },
      options);
    }




export const getAuthControllerMeV1QueryKey = () => {
    return [
    `/api/v1/auth/me`
    ] as const;
    }


export const getAuthControllerMeV1QueryOptions = <TData = Awaited<ReturnType<typeof authControllerMeV1>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMeV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerMeV1QueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerMeV1>>> = ({ signal }) => authControllerMeV1(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerMeV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerMeV1QueryResult = NonNullable<Awaited<ReturnType<typeof authControllerMeV1>>>
export type AuthControllerMeV1QueryError = unknown


export function useAuthControllerMeV1<TData = Awaited<ReturnType<typeof authControllerMeV1>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMeV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerMeV1>>,
          TError,
          Awaited<ReturnType<typeof authControllerMeV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerMeV1<TData = Awaited<ReturnType<typeof authControllerMeV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMeV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerMeV1>>,
          TError,
          Awaited<ReturnType<typeof authControllerMeV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerMeV1<TData = Awaited<ReturnType<typeof authControllerMeV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMeV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 현재 로그인한 사용자 프로필 정보 조회
 */

export function useAuthControllerMeV1<TData = Awaited<ReturnType<typeof authControllerMeV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMeV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerMeV1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






