/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary 서비스 설정 조회
 */
export const ServiceConfigControllerGetConfigsV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "operation": zod.object({
  "hours": zod.object({
  "start": zod.string().describe('운영 시작 시각 (HH:mm)'),
  "end": zod.string().describe('운영 종료 시각 (HH:mm)'),
  "openDays": zod.array(zod.number()).describe('운영 요일 (0: 일, 1: 월 ... 6: 토)'),
  "lunchBreak": zod.object({
  "enabled": zod.boolean().describe('점심시간 활성화 여부'),
  "start": zod.string().describe('점심시간 시작 시각 (HH:mm)'),
  "end": zod.string().describe('점심시간 종료 시각 (HH:mm)')
}).describe('점심\/휴게시간 설정')
}).describe('운영 시간 설정'),
  "holidays": zod.array(zod.object({
  "date": zod.string().describe('공휴일 날짜 (YYYY-MM-DD)'),
  "name": zod.string().describe('공휴일\/휴무 명칭'),
  "type": zod.enum(['STATUTORY', 'CUSTOM']).describe('공휴일 구분 (STATUTORY: 법정공휴일, CUSTOM: 특별지정휴일)').describe('공휴일 구분 (STATUTORY: 법정공휴일, CUSTOM: 특별지정휴일)')
})).describe('공휴일 및 특별 휴무일 목록'),
  "messages": zod.object({
  "lunch": zod.string().describe('점심시간 안내 문구'),
  "offHours": zod.string().describe('운영시간 외 안내 문구'),
  "holiday": zod.string().describe('휴일 안내 문구')
}).describe('운영 상태별 안내 메시지')
}),
  "maintenance": zod.object({
  "temporary": zod.object({
  "enabled": zod.boolean().describe('임시 점검 활성화 여부'),
  "message": zod.string().describe('임시 점검 안내 문구'),
  "startAt": zod.string().nullish().describe('임시 점검 시작 일시 (ISO 8601, 미지정 시 즉시 시작)'),
  "endAt": zod.string().nullish().describe('임시 점검 종료 일시 (ISO 8601, 미지정 시 수동 해제 전까지 유지)')
}).describe('임시 점검 설정'),
  "recurring": zod.object({
  "enabled": zod.boolean().describe('정기 점검 활성화 여부'),
  "message": zod.string().describe('정기 점검 안내 문구'),
  "daysOfWeek": zod.array(zod.number()).describe('정기 점검 반복 요일 (0: 일, 1: 월 ... 6: 토)'),
  "startTime": zod.string().describe('정기 점검 시작 시각 (HH:mm)'),
  "endTime": zod.string().describe('정기 점검 종료 시각 (HH:mm)')
}).describe('정기 점검 설정')
}),
  "inquiry": zod.object({
  "customerGreeting": zod.string().describe('새 고객지원 상담에 표시할 첫 안내 문구 (최대 500자)'),
  "offlineReplyMessage": zod.string().describe('운영시간 외 고객 메시지에 표시할 부재중 응답 문구 (최대 500자)'),
  "unansweredThresholdMinutes": zod.number().describe('미응답 문의 감지 기준 시간 (분)'),
  "autoCloseHours": zod.number().describe('문의 자동 종료 기준 시간 (시간)')
})
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * @summary 서비스 설정 전체 수정
 */
export const ServiceConfigControllerUpdateConfigsV1Body = zod.object({
  "operation": zod.object({
  "hours": zod.object({
  "start": zod.string().describe('운영 시작 시각 (HH:mm)'),
  "end": zod.string().describe('운영 종료 시각 (HH:mm)'),
  "openDays": zod.array(zod.number()).describe('운영 요일 (0: 일, 1: 월 ... 6: 토)'),
  "lunchBreak": zod.object({
  "enabled": zod.boolean().describe('점심시간 활성화 여부'),
  "start": zod.string().describe('점심시간 시작 시각 (HH:mm)'),
  "end": zod.string().describe('점심시간 종료 시각 (HH:mm)')
}).describe('점심\/휴게시간 설정')
}).describe('운영 시간 설정'),
  "holidays": zod.array(zod.object({
  "date": zod.string().describe('공휴일 날짜 (YYYY-MM-DD)'),
  "name": zod.string().describe('공휴일\/휴무 명칭'),
  "type": zod.enum(['STATUTORY', 'CUSTOM']).describe('공휴일 구분 (STATUTORY: 법정공휴일, CUSTOM: 특별지정휴일)').describe('공휴일 구분 (STATUTORY: 법정공휴일, CUSTOM: 특별지정휴일)')
})).describe('공휴일 및 특별 휴무일 목록'),
  "messages": zod.object({
  "lunch": zod.string().describe('점심시간 안내 문구'),
  "offHours": zod.string().describe('운영시간 외 안내 문구'),
  "holiday": zod.string().describe('휴일 안내 문구')
}).describe('운영 상태별 안내 메시지')
}).optional(),
  "maintenance": zod.object({
  "temporary": zod.object({
  "enabled": zod.boolean().describe('임시 점검 활성화 여부'),
  "message": zod.string().describe('임시 점검 안내 문구'),
  "startAt": zod.string().nullish().describe('임시 점검 시작 일시 (ISO 8601, 미지정 시 즉시 시작)'),
  "endAt": zod.string().nullish().describe('임시 점검 종료 일시 (ISO 8601, 미지정 시 수동 해제 전까지 유지)')
}).describe('임시 점검 설정'),
  "recurring": zod.object({
  "enabled": zod.boolean().describe('정기 점검 활성화 여부'),
  "message": zod.string().describe('정기 점검 안내 문구'),
  "daysOfWeek": zod.array(zod.number()).describe('정기 점검 반복 요일 (0: 일, 1: 월 ... 6: 토)'),
  "startTime": zod.string().describe('정기 점검 시작 시각 (HH:mm)'),
  "endTime": zod.string().describe('정기 점검 종료 시각 (HH:mm)')
}).describe('정기 점검 설정')
}).optional(),
  "inquiry": zod.object({
  "customerGreeting": zod.string().describe('새 고객지원 상담에 표시할 첫 안내 문구 (최대 500자)'),
  "offlineReplyMessage": zod.string().describe('운영시간 외 고객 메시지에 표시할 부재중 응답 문구 (최대 500자)'),
  "unansweredThresholdMinutes": zod.number().describe('미응답 문의 감지 기준 시간 (분)'),
  "autoCloseHours": zod.number().describe('문의 자동 종료 기준 시간 (시간)')
}).optional()
})

export const ServiceConfigControllerUpdateConfigsV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean(),
  "updatedKeys": zod.array(zod.enum(['operation', 'maintenance', 'inquiry', 'webhook', 'delivery', 'oauth']))
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * @summary 법정 공휴일 조회
 */
export const ServiceConfigControllerGetHolidaysV1QueryParams = zod.object({
  "year": zod.number().optional().describe('조회 대상 연도 (생략 시 현재 연도)')
})

export const ServiceConfigControllerGetHolidaysV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "year": zod.number(),
  "count": zod.number(),
  "holidays": zod.array(zod.object({
  "date": zod.string().describe('공휴일 날짜 (YYYY-MM-DD)'),
  "name": zod.string().describe('공휴일\/휴무 명칭'),
  "type": zod.enum(['STATUTORY', 'CUSTOM']).describe('공휴일 구분 (STATUTORY: 법정공휴일, CUSTOM: 특별지정휴일)').describe('공휴일 구분 (STATUTORY: 법정공휴일, CUSTOM: 특별지정휴일)')
}))
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

