/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary 공개 공지사항 목록 조회
 */
export const noticesControllerListV1QueryLimitDefault = 20;

export const NoticesControllerListV1QueryParams = zod.object({
  "sort": zod.array(zod.string()).optional(),
  "direction": zod.array(zod.enum(['asc', 'desc'])).optional(),
  "search": zod.string().optional(),
  "cursor": zod.string().nullish(),
  "limit": zod.number().default(noticesControllerListV1QueryLimitDefault),
  "importance": zod.enum(['normal', 'important', 'urgent']).optional()
})

export const NoticesControllerListV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "startCursor": zod.string().nullable(),
  "endCursor": zod.string().nullable(),
  "hasNextPage": zod.boolean(),
  "hasPrevPage": zod.boolean(),
  "totalCount": zod.number(),
  "items": zod.array(zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "content": zod.string(),
  "importance": zod.enum(['normal', 'important', 'urgent']),
  "isPinned": zod.boolean(),
  "status": zod.enum(['draft', 'published']),
  "publishedAt": zod.iso.datetime({"offset":true}).nullable(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}))
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * @summary 공개 공지사항 상세 조회
 */
export const NoticesControllerDetailV1Params = zod.object({
  "id": zod.string()
})

export const NoticesControllerDetailV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "content": zod.string(),
  "importance": zod.enum(['normal', 'important', 'urgent']),
  "isPinned": zod.boolean(),
  "status": zod.enum(['draft', 'published']),
  "publishedAt": zod.iso.datetime({"offset":true}).nullable(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

