/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Validation error details containing fields mapping
 * @nullable
 */
export type ApiErrorResponseDtoDetails = { [key: string]: unknown } | null;
