/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { AuthControllerUnregisterV1200Meta } from './authControllerUnregisterV1200Meta';
import type { UnregisterResponseDto } from './unregisterResponseDto';

export type AuthControllerUnregisterV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: UnregisterResponseDto;
  message?: string;
  meta?: AuthControllerUnregisterV1200Meta;
};
