/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { AuthControllerCompleteTwoFactorLoginV1200Meta } from './authControllerCompleteTwoFactorLoginV1200Meta';
import type { LoginResponse } from './loginResponse';

export type AuthControllerCompleteTwoFactorLoginV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: LoginResponse;
  message?: string;
  meta?: AuthControllerCompleteTwoFactorLoginV1200Meta;
};
