/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */

export interface AuthPolicyResponseDto {
  emailVerificationRequired: boolean;
  passwordMinLength: number;
  passwordMaxLength: number;
  passwordMaxBytes: number;
  passwordRequiresNumbers: boolean;
  passwordRequiresSpecialChar: boolean;
  passwordRequiresUppercase: boolean;
  twoFactorAvailable: boolean;
  twoFactorCodeLength: number;
}
