/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { CustomersControllerListCustomerPiiV1SortItem } from './customersControllerListCustomerPiiV1SortItem';
import type { SortDirection } from './sortDirection';

export type CustomersControllerListCustomerPiiV1Params = {
sort?: CustomersControllerListCustomerPiiV1SortItem[];
direction?: SortDirection[];
search?: string;
page?: number;
limit?: number;
};
