/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { AdminCustomerActionResponse } from './adminCustomerActionResponse';
import type { CustomersControllerUpdateCustomerMemoV1200Meta } from './customersControllerUpdateCustomerMemoV1200Meta';

export type CustomersControllerUpdateCustomerMemoV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: AdminCustomerActionResponse;
  message?: string;
  meta?: CustomersControllerUpdateCustomerMemoV1200Meta;
};
