/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { EventPageResponseDto } from './eventPageResponseDto';
import type { EventsControllerListV1200Meta } from './eventsControllerListV1200Meta';

export type EventsControllerListV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: EventPageResponseDto;
  message?: string;
  meta?: EventsControllerListV1200Meta;
};
