/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */

export type FaqsControllerListFaqsV1Params = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * 고객 이름 또는 이메일 검색어
 */
search?: string;
/**
 * FAQ 카테고리
 */
category?: string;
};
