/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { FaqItemDto } from './faqItemDto';
import type { FaqsControllerUpdateFaqV1200Meta } from './faqsControllerUpdateFaqV1200Meta';

export type FaqsControllerUpdateFaqV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: FaqItemDto;
  message?: string;
  meta?: FaqsControllerUpdateFaqV1200Meta;
};
