/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */

export interface GenerateTwoFactorResponseDto {
  secret: string;
  /** 인증 앱에서 생성해야 하는 코드 길이 */
  codeLength: number;
  /** 인증 앱에서 생성해야 하는 코드 유효 주기(초) */
  periodSeconds: number;
}
