/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { OperatingHolidayItemDto } from './operatingHolidayItemDto';

export interface GetHolidaysResponseDto {
  year: number;
  count: number;
  holidays: OperatingHolidayItemDto[];
}
