/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */

export type HealthControllerCheckV1503DetailsStatus = typeof HealthControllerCheckV1503DetailsStatus[keyof typeof HealthControllerCheckV1503DetailsStatus];


export const HealthControllerCheckV1503DetailsStatus = {
  up: 'up',
  degraded: 'degraded',
  down: 'down',
} as const;
