/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */

export type HealthControllerCheckReady503Status = typeof HealthControllerCheckReady503Status[keyof typeof HealthControllerCheckReady503Status];


export const HealthControllerCheckReady503Status = {
  error: 'error',
  shutting_down: 'shutting_down',
} as const;
