/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */

export interface LoginCredentialResponse {
  /** 초단기 액세스 토큰 (JWT) */
  accessToken: string;
  /** 액세스 토큰 만료 시간 (초) */
  expiresIn: number;
  /** Refresh Token 만료 시간 (초) */
  refreshTokenExpiresIn: number;
  /** 순수 네이티브 앱용 Refresh Token (웹 브라우저는 HttpOnly 쿠키로 전달) */
  refreshToken?: string;
}
