/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */

export interface LogoutRequest {
  /** 모바일/외부 클라이언트용 Refresh Token (웹 브라우저는 쿠키 또는 Session Context 사용 시 생략 가능) */
  refreshToken?: string;
}
