/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { MembershipItemDto } from './membershipItemDto';
import type { MembershipsControllerUpdateV1200Meta } from './membershipsControllerUpdateV1200Meta';

export type MembershipsControllerUpdateV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: MembershipItemDto;
  message?: string;
  meta?: MembershipsControllerUpdateV1200Meta;
};
