/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { GetAgreementsResponseDto } from './getAgreementsResponseDto';
import type { OperatorTermsControllerGetAgreementsV1200Meta } from './operatorTermsControllerGetAgreementsV1200Meta';

export type OperatorTermsControllerGetAgreementsV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: GetAgreementsResponseDto;
  message?: string;
  meta?: OperatorTermsControllerGetAgreementsV1200Meta;
};
