/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { SortDirection } from './sortDirection';

export type OperatorTermsControllerGetAgreementHistoryV1Params = {
sort?: string[];
direction?: SortDirection[];
search?: string;
/**
 * @nullable
 */
cursor?: string | null;
/**
 * @maximum 100
 */
limit?: number;
};
