/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { OperatorActionResponse } from './operatorActionResponse';
import type { OperatorsControllerDeleteOperatorV1200Meta } from './operatorsControllerDeleteOperatorV1200Meta';

export type OperatorsControllerDeleteOperatorV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: OperatorActionResponse;
  message?: string;
  meta?: OperatorsControllerDeleteOperatorV1200Meta;
};
