/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { QnaControllerUpdateV1200Meta } from './qnaControllerUpdateV1200Meta';
import type { QnaItem } from './qnaItem';

export type QnaControllerUpdateV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: QnaItem;
  message?: string;
  meta?: QnaControllerUpdateV1200Meta;
};
