/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { QnaControllerListV1Priority } from './qnaControllerListV1Priority';
import type { QnaControllerListV1Status } from './qnaControllerListV1Status';

export type QnaControllerListV1Params = {
search?: string;
page?: unknown;
limit?: unknown;
status?: QnaControllerListV1Status;
priority?: QnaControllerListV1Priority;
};
