/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */

export interface RegistrationConfigDto {
  /** 전체 신규 회원가입 허용 여부 */
  allowRegistration: boolean;
  /** 로컬(이메일/비밀번호) 회원가입 허용 여부 */
  allowCredentialRegistration: boolean;
  /** 회원가입 시 이메일 인증 필수 여부 */
  requireEmailVerification: boolean;
}
