/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { AdminServiceTermListResponseDto } from './adminServiceTermListResponseDto';
import type { ServiceTermsControllerListV1200Meta } from './serviceTermsControllerListV1200Meta';

export type ServiceTermsControllerListV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: AdminServiceTermListResponseDto;
  message?: string;
  meta?: ServiceTermsControllerListV1200Meta;
};
