/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */

export type SupportControllerListRoomPiiV1SortItem = typeof SupportControllerListRoomPiiV1SortItem[keyof typeof SupportControllerListRoomPiiV1SortItem];


export const SupportControllerListRoomPiiV1SortItem = {
  lastMessageAt: 'lastMessageAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  id: 'id',
} as const;
