/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { SupportControllerListRoomsV1200Meta } from './supportControllerListRoomsV1200Meta';
import type { SupportRoomListResponseDto } from './supportRoomListResponseDto';

export type SupportControllerListRoomsV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: SupportRoomListResponseDto;
  message?: string;
  meta?: SupportControllerListRoomsV1200Meta;
};
