/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { SortDirection } from './sortDirection';
import type { SupportControllerListRoomsV1Status } from './supportControllerListRoomsV1Status';

export type SupportControllerListRoomsV1Params = {
sort?: string[];
direction?: SortDirection[];
search?: string;
page?: number;
limit?: number;
status?: SupportControllerListRoomsV1Status;
};
