/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmailConfigResponseDto } from './adminEmailConfigResponseDto';
import type { SystemConfigControllerGetAdminAccountRecoveryEmailConfigV1200Meta } from './systemConfigControllerGetAdminAccountRecoveryEmailConfigV1200Meta';

export type SystemConfigControllerGetAdminAccountRecoveryEmailConfigV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: AdminEmailConfigResponseDto;
  message?: string;
  meta?: SystemConfigControllerGetAdminAccountRecoveryEmailConfigV1200Meta;
};
