/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */

export interface TermRevisionItem {
  id: string;
  version: string;
  publishedAt: string;
  reason: string;
  summary: string;
  content: string;
}
