/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { PublishTermResponse } from './publishTermResponse';
import type { TermsControllerPublishTermV1200Meta } from './termsControllerPublishTermV1200Meta';

export type TermsControllerPublishTermV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: PublishTermResponse;
  message?: string;
  meta?: TermsControllerPublishTermV1200Meta;
};
