/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteTermResponseDto } from './deleteTermResponseDto';
import type { TermsControllerDeleteTermV1200Meta } from './termsControllerDeleteTermV1200Meta';

export type TermsControllerDeleteTermV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: DeleteTermResponseDto;
  message?: string;
  meta?: TermsControllerDeleteTermV1200Meta;
};
