/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */

export type UpdateNoticeRequestDtoStatus = typeof UpdateNoticeRequestDtoStatus[keyof typeof UpdateNoticeRequestDtoStatus];


export const UpdateNoticeRequestDtoStatus = {
  draft: 'draft',
  published: 'published',
} as const;
