/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { CreateUserResponseDto } from './createUserResponseDto';
import type { UsersControllerCreateUserV1201Meta } from './usersControllerCreateUserV1201Meta';

export type UsersControllerCreateUserV1201 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: CreateUserResponseDto;
  message?: string;
  meta?: UsersControllerCreateUserV1201Meta;
};
