/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import type { UserActionResponseDto } from './userActionResponseDto';
import type { UsersControllerResetUserTwoFactorV1200Meta } from './usersControllerResetUserTwoFactorV1200Meta';

export type UsersControllerResetUserTwoFactorV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: UserActionResponseDto;
  message?: string;
  meta?: UsersControllerResetUserTwoFactorV1200Meta;
};
