/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */

export interface VerifyIdentityRequestDto {
  /** @maxLength 200 */
  identityVerificationId: string;
}
