/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * User API
 * Control Plane User API Service
 * OpenAPI spec version: 1.0.0
 */
import type { AuthControllerLoginV1200Meta } from './authControllerLoginV1200Meta';
import type { LoginResponse } from './loginResponse';

export type AuthControllerLoginV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: LoginResponse;
  message?: string;
  meta?: AuthControllerLoginV1200Meta;
};
