/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * User API
 * Control Plane User API Service
 * OpenAPI spec version: 1.0.0
 */

export type HealthControllerCheckV1200Status = typeof HealthControllerCheckV1200Status[keyof typeof HealthControllerCheckV1200Status];


export const HealthControllerCheckV1200Status = {
  ok: 'ok',
  degraded: 'degraded',
} as const;
