/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * User API
 * Control Plane User API Service
 * OpenAPI spec version: 1.0.0
 */
import type { SetAgreementItemDto } from './setAgreementItemDto';

export interface SetAgreementsRequestDto {
  agreements: SetAgreementItemDto[];
}
