/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateFaqRequestDto,
  FaqsControllerCreateFaq201,
  FaqsControllerDeleteFaq200,
  FaqsControllerGetAdminFaqs200,
  FaqsControllerGetAdminFaqsParams,
  FaqsControllerGetFaqs200,
  FaqsControllerGetFaqsParams,
  FaqsControllerUpdateFaq200,
  UpdateFaqRequestDto
} from '../../model';

import { axios } from '../../../../core/config/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const faqsControllerGetFaqs = (
    params?: FaqsControllerGetFaqsParams,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<FaqsControllerGetFaqs200>(
      {url: `/api/v1/faqs`, method: 'GET',
        params, signal
    },
      options);
    }




export const getFaqsControllerGetFaqsQueryKey = (params?: FaqsControllerGetFaqsParams,) => {
    return [
    `/api/v1/faqs`, ...(params ? [params] : [])
    ] as const;
    }


export const getFaqsControllerGetFaqsQueryOptions = <TData = Awaited<ReturnType<typeof faqsControllerGetFaqs>>, TError = unknown>(params?: FaqsControllerGetFaqsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof faqsControllerGetFaqs>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFaqsControllerGetFaqsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof faqsControllerGetFaqs>>> = ({ signal }) => faqsControllerGetFaqs(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof faqsControllerGetFaqs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FaqsControllerGetFaqsQueryResult = NonNullable<Awaited<ReturnType<typeof faqsControllerGetFaqs>>>
export type FaqsControllerGetFaqsQueryError = unknown


export function useFaqsControllerGetFaqs<TData = Awaited<ReturnType<typeof faqsControllerGetFaqs>>, TError = unknown>(
 params: undefined |  FaqsControllerGetFaqsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof faqsControllerGetFaqs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof faqsControllerGetFaqs>>,
          TError,
          Awaited<ReturnType<typeof faqsControllerGetFaqs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFaqsControllerGetFaqs<TData = Awaited<ReturnType<typeof faqsControllerGetFaqs>>, TError = unknown>(
 params?: FaqsControllerGetFaqsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof faqsControllerGetFaqs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof faqsControllerGetFaqs>>,
          TError,
          Awaited<ReturnType<typeof faqsControllerGetFaqs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFaqsControllerGetFaqs<TData = Awaited<ReturnType<typeof faqsControllerGetFaqs>>, TError = unknown>(
 params?: FaqsControllerGetFaqsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof faqsControllerGetFaqs>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFaqsControllerGetFaqs<TData = Awaited<ReturnType<typeof faqsControllerGetFaqs>>, TError = unknown>(
 params?: FaqsControllerGetFaqsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof faqsControllerGetFaqs>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFaqsControllerGetFaqsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const faqsControllerGetAdminFaqs = (
    params?: FaqsControllerGetAdminFaqsParams,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<FaqsControllerGetAdminFaqs200>(
      {url: `/api/v1/faqs/admin`, method: 'GET',
        params, signal
    },
      options);
    }




export const getFaqsControllerGetAdminFaqsQueryKey = (params?: FaqsControllerGetAdminFaqsParams,) => {
    return [
    `/api/v1/faqs/admin`, ...(params ? [params] : [])
    ] as const;
    }


export const getFaqsControllerGetAdminFaqsQueryOptions = <TData = Awaited<ReturnType<typeof faqsControllerGetAdminFaqs>>, TError = unknown>(params?: FaqsControllerGetAdminFaqsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof faqsControllerGetAdminFaqs>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFaqsControllerGetAdminFaqsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof faqsControllerGetAdminFaqs>>> = ({ signal }) => faqsControllerGetAdminFaqs(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof faqsControllerGetAdminFaqs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FaqsControllerGetAdminFaqsQueryResult = NonNullable<Awaited<ReturnType<typeof faqsControllerGetAdminFaqs>>>
export type FaqsControllerGetAdminFaqsQueryError = unknown


export function useFaqsControllerGetAdminFaqs<TData = Awaited<ReturnType<typeof faqsControllerGetAdminFaqs>>, TError = unknown>(
 params: undefined |  FaqsControllerGetAdminFaqsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof faqsControllerGetAdminFaqs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof faqsControllerGetAdminFaqs>>,
          TError,
          Awaited<ReturnType<typeof faqsControllerGetAdminFaqs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFaqsControllerGetAdminFaqs<TData = Awaited<ReturnType<typeof faqsControllerGetAdminFaqs>>, TError = unknown>(
 params?: FaqsControllerGetAdminFaqsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof faqsControllerGetAdminFaqs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof faqsControllerGetAdminFaqs>>,
          TError,
          Awaited<ReturnType<typeof faqsControllerGetAdminFaqs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFaqsControllerGetAdminFaqs<TData = Awaited<ReturnType<typeof faqsControllerGetAdminFaqs>>, TError = unknown>(
 params?: FaqsControllerGetAdminFaqsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof faqsControllerGetAdminFaqs>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFaqsControllerGetAdminFaqs<TData = Awaited<ReturnType<typeof faqsControllerGetAdminFaqs>>, TError = unknown>(
 params?: FaqsControllerGetAdminFaqsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof faqsControllerGetAdminFaqs>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFaqsControllerGetAdminFaqsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const faqsControllerCreateFaq = (
    createFaqRequestDto: CreateFaqRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<FaqsControllerCreateFaq201>(
      {url: `/api/v1/faqs/admin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFaqRequestDto, signal
    },
      options);
    }




export const getFaqsControllerCreateFaqMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof faqsControllerCreateFaq>>, TError,{data: CreateFaqRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof faqsControllerCreateFaq>>, TError,{data: CreateFaqRequestDto}, TContext> => {

const mutationKey = ['faqsControllerCreateFaq'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof faqsControllerCreateFaq>>, {data: CreateFaqRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  faqsControllerCreateFaq(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FaqsControllerCreateFaqMutationResult = NonNullable<Awaited<ReturnType<typeof faqsControllerCreateFaq>>>
    export type FaqsControllerCreateFaqMutationBody = CreateFaqRequestDto
    export type FaqsControllerCreateFaqMutationError = unknown

    export const useFaqsControllerCreateFaq = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof faqsControllerCreateFaq>>, TError,{data: CreateFaqRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof faqsControllerCreateFaq>>,
        TError,
        {data: CreateFaqRequestDto},
        TContext
      > => {
      return useMutation(getFaqsControllerCreateFaqMutationOptions(options), queryClient);
    }
    export const faqsControllerUpdateFaq = (
    id: string,
    updateFaqRequestDto: UpdateFaqRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<FaqsControllerUpdateFaq200>(
      {url: `/api/v1/faqs/admin/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateFaqRequestDto, signal
    },
      options);
    }




export const getFaqsControllerUpdateFaqMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof faqsControllerUpdateFaq>>, TError,{id: string;data: UpdateFaqRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof faqsControllerUpdateFaq>>, TError,{id: string;data: UpdateFaqRequestDto}, TContext> => {

const mutationKey = ['faqsControllerUpdateFaq'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof faqsControllerUpdateFaq>>, {id: string;data: UpdateFaqRequestDto}> = (props) => {
          const {id,data} = props ?? {};

          return  faqsControllerUpdateFaq(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FaqsControllerUpdateFaqMutationResult = NonNullable<Awaited<ReturnType<typeof faqsControllerUpdateFaq>>>
    export type FaqsControllerUpdateFaqMutationBody = UpdateFaqRequestDto
    export type FaqsControllerUpdateFaqMutationError = unknown

    export const useFaqsControllerUpdateFaq = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof faqsControllerUpdateFaq>>, TError,{id: string;data: UpdateFaqRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof faqsControllerUpdateFaq>>,
        TError,
        {id: string;data: UpdateFaqRequestDto},
        TContext
      > => {
      return useMutation(getFaqsControllerUpdateFaqMutationOptions(options), queryClient);
    }
    export const faqsControllerDeleteFaq = (
    id: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<FaqsControllerDeleteFaq200>(
      {url: `/api/v1/faqs/admin/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getFaqsControllerDeleteFaqMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof faqsControllerDeleteFaq>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof faqsControllerDeleteFaq>>, TError,{id: string}, TContext> => {

const mutationKey = ['faqsControllerDeleteFaq'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof faqsControllerDeleteFaq>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  faqsControllerDeleteFaq(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FaqsControllerDeleteFaqMutationResult = NonNullable<Awaited<ReturnType<typeof faqsControllerDeleteFaq>>>

    export type FaqsControllerDeleteFaqMutationError = unknown

    export const useFaqsControllerDeleteFaq = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof faqsControllerDeleteFaq>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof faqsControllerDeleteFaq>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getFaqsControllerDeleteFaqMutationOptions(options), queryClient);
    }
