/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AccountLinkRequestDto,
  AccountUnlinkRequestDto,
  AuthControllerAccountLink200,
  AuthControllerAccountUnlink200,
  AuthControllerChangePassword200,
  AuthControllerDeferPasswordChange200,
  AuthControllerFindId200,
  AuthControllerGenerate2FA200,
  AuthControllerGetEnabledProviders200,
  AuthControllerIssueEmailChangeChallenge200,
  AuthControllerIssuePasswordResetChallenge200,
  AuthControllerIssuePhoneChangeChallenge200,
  AuthControllerLogin200,
  AuthControllerLogout200,
  AuthControllerMe200,
  AuthControllerOauthCallbackParams,
  AuthControllerRegister201,
  AuthControllerResetPassword200,
  AuthControllerSyncAnalyticsConsent200,
  AuthControllerTurnOff2FA200,
  AuthControllerTurnOn2FA200,
  AuthControllerUserUnregister200,
  AuthControllerVerify2FAChallenge200,
  AuthControllerVerifyEmailChange200,
  AuthControllerVerifyIdentityPhoneChange200,
  AuthControllerVerifyPasswordResetToken200,
  AuthControllerVerifyPasswordResetTokenParams,
  ChangePasswordRequest,
  FindIdRequest,
  IssueEmailChangeChallengeRequestDto,
  IssuePasswordResetChallengeRequest,
  IssuePhoneChangeChallengeRequestDto,
  LoginRequest,
  RegisterRequest,
  ResetPasswordRequest,
  SyncAnalyticsConsentRequestDto,
  TwoFactorTurnOnRequestDto,
  TwoFactorVerifyChallengeRequestDto,
  VerifyEmailChangeRequestDto,
  VerifyIdentityPhoneChangeRequestDto
} from '../../model';

import { axios } from '../../../../core/config/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * 시스템 설정에서 활성화되고 인증 정보가 구성된 OAuth 제공자 목록을 반환합니다.
 * @summary 활성화된 OAuth 로그인 제공자 목록 조회
 */
export const authControllerGetEnabledProviders = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerGetEnabledProviders200>(
      {url: `/api/v1/auth/providers`, method: 'GET', signal
    },
      options);
    }




export const getAuthControllerGetEnabledProvidersQueryKey = () => {
    return [
    `/api/v1/auth/providers`
    ] as const;
    }


export const getAuthControllerGetEnabledProvidersQueryOptions = <TData = Awaited<ReturnType<typeof authControllerGetEnabledProviders>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetEnabledProviders>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerGetEnabledProvidersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGetEnabledProviders>>> = ({ signal }) => authControllerGetEnabledProviders(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerGetEnabledProviders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerGetEnabledProvidersQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerGetEnabledProviders>>>
export type AuthControllerGetEnabledProvidersQueryError = unknown


export function useAuthControllerGetEnabledProviders<TData = Awaited<ReturnType<typeof authControllerGetEnabledProviders>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetEnabledProviders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetEnabledProviders>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetEnabledProviders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerGetEnabledProviders<TData = Awaited<ReturnType<typeof authControllerGetEnabledProviders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetEnabledProviders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetEnabledProviders>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetEnabledProviders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerGetEnabledProviders<TData = Awaited<ReturnType<typeof authControllerGetEnabledProviders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetEnabledProviders>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 활성화된 OAuth 로그인 제공자 목록 조회
 */

export function useAuthControllerGetEnabledProviders<TData = Awaited<ReturnType<typeof authControllerGetEnabledProviders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetEnabledProviders>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerGetEnabledProvidersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * 지정된 OAuth 제공자(google, kakao, naver, github)의 인가 페이지로 리다이렉트합니다.
 * @summary 동적 OAuth 인가 요청
 */
export const authControllerOauthLogin = (
    provider: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<void>(
      {url: `/api/v1/auth/oauth/${provider}`, method: 'GET', signal
    },
      options);
    }




export const getAuthControllerOauthLoginQueryKey = (provider: string,) => {
    return [
    `/api/v1/auth/oauth/${provider}`
    ] as const;
    }


export const getAuthControllerOauthLoginQueryOptions = <TData = Awaited<ReturnType<typeof authControllerOauthLogin>>, TError = unknown>(provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerOauthLogin>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerOauthLoginQueryKey(provider);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerOauthLogin>>> = ({ signal }) => authControllerOauthLogin(provider, requestOptions, signal);





   return  { queryKey, queryFn, enabled: provider !== null && provider !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerOauthLogin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerOauthLoginQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerOauthLogin>>>
export type AuthControllerOauthLoginQueryError = unknown


export function useAuthControllerOauthLogin<TData = Awaited<ReturnType<typeof authControllerOauthLogin>>, TError = unknown>(
 provider: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerOauthLogin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerOauthLogin>>,
          TError,
          Awaited<ReturnType<typeof authControllerOauthLogin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerOauthLogin<TData = Awaited<ReturnType<typeof authControllerOauthLogin>>, TError = unknown>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerOauthLogin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerOauthLogin>>,
          TError,
          Awaited<ReturnType<typeof authControllerOauthLogin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerOauthLogin<TData = Awaited<ReturnType<typeof authControllerOauthLogin>>, TError = unknown>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerOauthLogin>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 동적 OAuth 인가 요청
 */

export function useAuthControllerOauthLogin<TData = Awaited<ReturnType<typeof authControllerOauthLogin>>, TError = unknown>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerOauthLogin>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerOauthLoginQueryOptions(provider,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * 지정된 OAuth 제공자로부터의 인증 코드 및 상태를 검증하고 로그인을 처리한 후 프론트엔드로 리다이렉트합니다.
 * @summary 동적 OAuth 로그인 콜백
 */
export const authControllerOauthCallback = (
    provider: string,
    params?: AuthControllerOauthCallbackParams,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<void>(
      {url: `/api/v1/auth/oauth/${provider}/callback`, method: 'GET',
        params, signal
    },
      options);
    }




export const getAuthControllerOauthCallbackQueryKey = (provider: string,
    params?: AuthControllerOauthCallbackParams,) => {
    return [
    `/api/v1/auth/oauth/${provider}/callback`, ...(params ? [params] : [])
    ] as const;
    }


export const getAuthControllerOauthCallbackQueryOptions = <TData = Awaited<ReturnType<typeof authControllerOauthCallback>>, TError = unknown>(provider: string,
    params?: AuthControllerOauthCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerOauthCallback>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerOauthCallbackQueryKey(provider,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerOauthCallback>>> = ({ signal }) => authControllerOauthCallback(provider,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: provider !== null && provider !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerOauthCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerOauthCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerOauthCallback>>>
export type AuthControllerOauthCallbackQueryError = unknown


export function useAuthControllerOauthCallback<TData = Awaited<ReturnType<typeof authControllerOauthCallback>>, TError = unknown>(
 provider: string,
    params: undefined |  AuthControllerOauthCallbackParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerOauthCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerOauthCallback>>,
          TError,
          Awaited<ReturnType<typeof authControllerOauthCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerOauthCallback<TData = Awaited<ReturnType<typeof authControllerOauthCallback>>, TError = unknown>(
 provider: string,
    params?: AuthControllerOauthCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerOauthCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerOauthCallback>>,
          TError,
          Awaited<ReturnType<typeof authControllerOauthCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerOauthCallback<TData = Awaited<ReturnType<typeof authControllerOauthCallback>>, TError = unknown>(
 provider: string,
    params?: AuthControllerOauthCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerOauthCallback>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 동적 OAuth 로그인 콜백
 */

export function useAuthControllerOauthCallback<TData = Awaited<ReturnType<typeof authControllerOauthCallback>>, TError = unknown>(
 provider: string,
    params?: AuthControllerOauthCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerOauthCallback>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerOauthCallbackQueryOptions(provider,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const authControllerLogin = (
    loginRequest: LoginRequest,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerLogin200>(
      {url: `/api/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      options);
    }




export const getAuthControllerLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['authControllerLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogin>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>
    export type AuthControllerLoginMutationBody = LoginRequest
    export type AuthControllerLoginMutationError = unknown

    export const useAuthControllerLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogin>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {
      return useMutation(getAuthControllerLoginMutationOptions(options), queryClient);
    }
    export const authControllerRegister = (
    registerRequest: RegisterRequest,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerRegister201>(
      {url: `/api/v1/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerRequest, signal
    },
      options);
    }




export const getAuthControllerRegisterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError,{data: RegisterRequest}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['authControllerRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRegister>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerRegister(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRegister>>>
    export type AuthControllerRegisterMutationBody = RegisterRequest
    export type AuthControllerRegisterMutationError = unknown

    export const useAuthControllerRegister = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError,{data: RegisterRequest}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerRegister>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {
      return useMutation(getAuthControllerRegisterMutationOptions(options), queryClient);
    }
    export const authControllerVerify2FAChallenge = (
    twoFactorVerifyChallengeRequestDto: TwoFactorVerifyChallengeRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerVerify2FAChallenge200>(
      {url: `/api/v1/auth/2fa/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: twoFactorVerifyChallengeRequestDto, signal
    },
      options);
    }




export const getAuthControllerVerify2FAChallengeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerVerify2FAChallenge>>, TError,{data: TwoFactorVerifyChallengeRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerVerify2FAChallenge>>, TError,{data: TwoFactorVerifyChallengeRequestDto}, TContext> => {

const mutationKey = ['authControllerVerify2FAChallenge'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerVerify2FAChallenge>>, {data: TwoFactorVerifyChallengeRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerVerify2FAChallenge(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerVerify2FAChallengeMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerVerify2FAChallenge>>>
    export type AuthControllerVerify2FAChallengeMutationBody = TwoFactorVerifyChallengeRequestDto
    export type AuthControllerVerify2FAChallengeMutationError = unknown

    export const useAuthControllerVerify2FAChallenge = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerVerify2FAChallenge>>, TError,{data: TwoFactorVerifyChallengeRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerVerify2FAChallenge>>,
        TError,
        {data: TwoFactorVerifyChallengeRequestDto},
        TContext
      > => {
      return useMutation(getAuthControllerVerify2FAChallengeMutationOptions(options), queryClient);
    }
    export const authControllerLogout = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerLogout200>(
      {url: `/api/v1/auth/logout`, method: 'POST', signal
    },
      options);
    }




export const getAuthControllerLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext> => {

const mutationKey = ['authControllerLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogout>>, void> = () => {


          return  authControllerLogout(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogout>>>

    export type AuthControllerLogoutMutationError = unknown

    export const useAuthControllerLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerLogoutMutationOptions(options), queryClient);
    }
    export const authControllerSyncAnalyticsConsent = (
    syncAnalyticsConsentRequestDto: SyncAnalyticsConsentRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerSyncAnalyticsConsent200>(
      {url: `/api/v1/auth/consent/sync`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: syncAnalyticsConsentRequestDto, signal
    },
      options);
    }




export const getAuthControllerSyncAnalyticsConsentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerSyncAnalyticsConsent>>, TError,{data: SyncAnalyticsConsentRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerSyncAnalyticsConsent>>, TError,{data: SyncAnalyticsConsentRequestDto}, TContext> => {

const mutationKey = ['authControllerSyncAnalyticsConsent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerSyncAnalyticsConsent>>, {data: SyncAnalyticsConsentRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerSyncAnalyticsConsent(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerSyncAnalyticsConsentMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerSyncAnalyticsConsent>>>
    export type AuthControllerSyncAnalyticsConsentMutationBody = SyncAnalyticsConsentRequestDto
    export type AuthControllerSyncAnalyticsConsentMutationError = unknown

    export const useAuthControllerSyncAnalyticsConsent = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerSyncAnalyticsConsent>>, TError,{data: SyncAnalyticsConsentRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerSyncAnalyticsConsent>>,
        TError,
        {data: SyncAnalyticsConsentRequestDto},
        TContext
      > => {
      return useMutation(getAuthControllerSyncAnalyticsConsentMutationOptions(options), queryClient);
    }
    export const authControllerMe = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerMe200>(
      {url: `/api/v1/auth/me`, method: 'GET', signal
    },
      options);
    }




export const getAuthControllerMeQueryKey = () => {
    return [
    `/api/v1/auth/me`
    ] as const;
    }


export const getAuthControllerMeQueryOptions = <TData = Awaited<ReturnType<typeof authControllerMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerMe>>> = ({ signal }) => authControllerMe(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerMeQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerMe>>>
export type AuthControllerMeQueryError = unknown


export function useAuthControllerMe<TData = Awaited<ReturnType<typeof authControllerMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerMe>>,
          TError,
          Awaited<ReturnType<typeof authControllerMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerMe<TData = Awaited<ReturnType<typeof authControllerMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerMe>>,
          TError,
          Awaited<ReturnType<typeof authControllerMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerMe<TData = Awaited<ReturnType<typeof authControllerMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAuthControllerMe<TData = Awaited<ReturnType<typeof authControllerMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const authControllerAccountLink = (
    accountLinkRequestDto: AccountLinkRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerAccountLink200>(
      {url: `/api/v1/auth/link-account`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: accountLinkRequestDto, signal
    },
      options);
    }




export const getAuthControllerAccountLinkMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerAccountLink>>, TError,{data: AccountLinkRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerAccountLink>>, TError,{data: AccountLinkRequestDto}, TContext> => {

const mutationKey = ['authControllerAccountLink'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerAccountLink>>, {data: AccountLinkRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerAccountLink(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerAccountLinkMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerAccountLink>>>
    export type AuthControllerAccountLinkMutationBody = AccountLinkRequestDto
    export type AuthControllerAccountLinkMutationError = unknown

    export const useAuthControllerAccountLink = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerAccountLink>>, TError,{data: AccountLinkRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerAccountLink>>,
        TError,
        {data: AccountLinkRequestDto},
        TContext
      > => {
      return useMutation(getAuthControllerAccountLinkMutationOptions(options), queryClient);
    }
    export const authControllerAccountUnlink = (
    accountUnlinkRequestDto: AccountUnlinkRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerAccountUnlink200>(
      {url: `/api/v1/auth/unlink-account`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: accountUnlinkRequestDto, signal
    },
      options);
    }




export const getAuthControllerAccountUnlinkMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerAccountUnlink>>, TError,{data: AccountUnlinkRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerAccountUnlink>>, TError,{data: AccountUnlinkRequestDto}, TContext> => {

const mutationKey = ['authControllerAccountUnlink'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerAccountUnlink>>, {data: AccountUnlinkRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerAccountUnlink(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerAccountUnlinkMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerAccountUnlink>>>
    export type AuthControllerAccountUnlinkMutationBody = AccountUnlinkRequestDto
    export type AuthControllerAccountUnlinkMutationError = unknown

    export const useAuthControllerAccountUnlink = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerAccountUnlink>>, TError,{data: AccountUnlinkRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerAccountUnlink>>,
        TError,
        {data: AccountUnlinkRequestDto},
        TContext
      > => {
      return useMutation(getAuthControllerAccountUnlinkMutationOptions(options), queryClient);
    }
    export const authControllerUserUnregister = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerUserUnregister200>(
      {url: `/api/v1/auth/unregister`, method: 'POST', signal
    },
      options);
    }




export const getAuthControllerUserUnregisterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerUserUnregister>>, TError,void, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerUserUnregister>>, TError,void, TContext> => {

const mutationKey = ['authControllerUserUnregister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerUserUnregister>>, void> = () => {


          return  authControllerUserUnregister(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerUserUnregisterMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerUserUnregister>>>

    export type AuthControllerUserUnregisterMutationError = unknown

    export const useAuthControllerUserUnregister = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerUserUnregister>>, TError,void, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerUserUnregister>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerUserUnregisterMutationOptions(options), queryClient);
    }
    export const authControllerGenerate2FA = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerGenerate2FA200>(
      {url: `/api/v1/auth/2fa/generate`, method: 'POST', signal
    },
      options);
    }




export const getAuthControllerGenerate2FAMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGenerate2FA>>, TError,void, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerGenerate2FA>>, TError,void, TContext> => {

const mutationKey = ['authControllerGenerate2FA'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerGenerate2FA>>, void> = () => {


          return  authControllerGenerate2FA(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerGenerate2FAMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerGenerate2FA>>>

    export type AuthControllerGenerate2FAMutationError = unknown

    export const useAuthControllerGenerate2FA = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGenerate2FA>>, TError,void, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerGenerate2FA>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerGenerate2FAMutationOptions(options), queryClient);
    }
    export const authControllerTurnOn2FA = (
    twoFactorTurnOnRequestDto: TwoFactorTurnOnRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerTurnOn2FA200>(
      {url: `/api/v1/auth/2fa/turn-on`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: twoFactorTurnOnRequestDto, signal
    },
      options);
    }




export const getAuthControllerTurnOn2FAMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerTurnOn2FA>>, TError,{data: TwoFactorTurnOnRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerTurnOn2FA>>, TError,{data: TwoFactorTurnOnRequestDto}, TContext> => {

const mutationKey = ['authControllerTurnOn2FA'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerTurnOn2FA>>, {data: TwoFactorTurnOnRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerTurnOn2FA(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerTurnOn2FAMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerTurnOn2FA>>>
    export type AuthControllerTurnOn2FAMutationBody = TwoFactorTurnOnRequestDto
    export type AuthControllerTurnOn2FAMutationError = unknown

    export const useAuthControllerTurnOn2FA = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerTurnOn2FA>>, TError,{data: TwoFactorTurnOnRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerTurnOn2FA>>,
        TError,
        {data: TwoFactorTurnOnRequestDto},
        TContext
      > => {
      return useMutation(getAuthControllerTurnOn2FAMutationOptions(options), queryClient);
    }
    export const authControllerTurnOff2FA = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerTurnOff2FA200>(
      {url: `/api/v1/auth/2fa/turn-off`, method: 'POST', signal
    },
      options);
    }




export const getAuthControllerTurnOff2FAMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerTurnOff2FA>>, TError,void, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerTurnOff2FA>>, TError,void, TContext> => {

const mutationKey = ['authControllerTurnOff2FA'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerTurnOff2FA>>, void> = () => {


          return  authControllerTurnOff2FA(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerTurnOff2FAMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerTurnOff2FA>>>

    export type AuthControllerTurnOff2FAMutationError = unknown

    export const useAuthControllerTurnOff2FA = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerTurnOff2FA>>, TError,void, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerTurnOff2FA>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerTurnOff2FAMutationOptions(options), queryClient);
    }
    export const authControllerChangePassword = (
    changePasswordRequest: ChangePasswordRequest,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerChangePassword200>(
      {url: `/api/v1/auth/password/change`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordRequest, signal
    },
      options);
    }




export const getAuthControllerChangePasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerChangePassword>>, TError,{data: ChangePasswordRequest}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerChangePassword>>, TError,{data: ChangePasswordRequest}, TContext> => {

const mutationKey = ['authControllerChangePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerChangePassword>>, {data: ChangePasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerChangePassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerChangePassword>>>
    export type AuthControllerChangePasswordMutationBody = ChangePasswordRequest
    export type AuthControllerChangePasswordMutationError = unknown

    export const useAuthControllerChangePassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerChangePassword>>, TError,{data: ChangePasswordRequest}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerChangePassword>>,
        TError,
        {data: ChangePasswordRequest},
        TContext
      > => {
      return useMutation(getAuthControllerChangePasswordMutationOptions(options), queryClient);
    }
    export const authControllerDeferPasswordChange = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerDeferPasswordChange200>(
      {url: `/api/v1/auth/password/defer`, method: 'POST', signal
    },
      options);
    }




export const getAuthControllerDeferPasswordChangeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerDeferPasswordChange>>, TError,void, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerDeferPasswordChange>>, TError,void, TContext> => {

const mutationKey = ['authControllerDeferPasswordChange'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerDeferPasswordChange>>, void> = () => {


          return  authControllerDeferPasswordChange(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerDeferPasswordChangeMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerDeferPasswordChange>>>

    export type AuthControllerDeferPasswordChangeMutationError = unknown

    export const useAuthControllerDeferPasswordChange = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerDeferPasswordChange>>, TError,void, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerDeferPasswordChange>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerDeferPasswordChangeMutationOptions(options), queryClient);
    }
    export const authControllerIssuePhoneChangeChallenge = (
    issuePhoneChangeChallengeRequestDto: IssuePhoneChangeChallengeRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerIssuePhoneChangeChallenge200>(
      {url: `/api/v1/auth/phone/change/challenge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: issuePhoneChangeChallengeRequestDto, signal
    },
      options);
    }




export const getAuthControllerIssuePhoneChangeChallengeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerIssuePhoneChangeChallenge>>, TError,{data: IssuePhoneChangeChallengeRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerIssuePhoneChangeChallenge>>, TError,{data: IssuePhoneChangeChallengeRequestDto}, TContext> => {

const mutationKey = ['authControllerIssuePhoneChangeChallenge'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerIssuePhoneChangeChallenge>>, {data: IssuePhoneChangeChallengeRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerIssuePhoneChangeChallenge(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerIssuePhoneChangeChallengeMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerIssuePhoneChangeChallenge>>>
    export type AuthControllerIssuePhoneChangeChallengeMutationBody = IssuePhoneChangeChallengeRequestDto
    export type AuthControllerIssuePhoneChangeChallengeMutationError = unknown

    export const useAuthControllerIssuePhoneChangeChallenge = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerIssuePhoneChangeChallenge>>, TError,{data: IssuePhoneChangeChallengeRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerIssuePhoneChangeChallenge>>,
        TError,
        {data: IssuePhoneChangeChallengeRequestDto},
        TContext
      > => {
      return useMutation(getAuthControllerIssuePhoneChangeChallengeMutationOptions(options), queryClient);
    }
    export const authControllerVerifyIdentityPhoneChange = (
    verifyIdentityPhoneChangeRequestDto: VerifyIdentityPhoneChangeRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerVerifyIdentityPhoneChange200>(
      {url: `/api/v1/auth/phone/change/identity`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyIdentityPhoneChangeRequestDto, signal
    },
      options);
    }




export const getAuthControllerVerifyIdentityPhoneChangeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerVerifyIdentityPhoneChange>>, TError,{data: VerifyIdentityPhoneChangeRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerVerifyIdentityPhoneChange>>, TError,{data: VerifyIdentityPhoneChangeRequestDto}, TContext> => {

const mutationKey = ['authControllerVerifyIdentityPhoneChange'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerVerifyIdentityPhoneChange>>, {data: VerifyIdentityPhoneChangeRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerVerifyIdentityPhoneChange(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerVerifyIdentityPhoneChangeMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerVerifyIdentityPhoneChange>>>
    export type AuthControllerVerifyIdentityPhoneChangeMutationBody = VerifyIdentityPhoneChangeRequestDto
    export type AuthControllerVerifyIdentityPhoneChangeMutationError = unknown

    export const useAuthControllerVerifyIdentityPhoneChange = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerVerifyIdentityPhoneChange>>, TError,{data: VerifyIdentityPhoneChangeRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerVerifyIdentityPhoneChange>>,
        TError,
        {data: VerifyIdentityPhoneChangeRequestDto},
        TContext
      > => {
      return useMutation(getAuthControllerVerifyIdentityPhoneChangeMutationOptions(options), queryClient);
    }
    export const authControllerIssueEmailChangeChallenge = (
    issueEmailChangeChallengeRequestDto: IssueEmailChangeChallengeRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerIssueEmailChangeChallenge200>(
      {url: `/api/v1/auth/email/change/challenge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: issueEmailChangeChallengeRequestDto, signal
    },
      options);
    }




export const getAuthControllerIssueEmailChangeChallengeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerIssueEmailChangeChallenge>>, TError,{data: IssueEmailChangeChallengeRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerIssueEmailChangeChallenge>>, TError,{data: IssueEmailChangeChallengeRequestDto}, TContext> => {

const mutationKey = ['authControllerIssueEmailChangeChallenge'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerIssueEmailChangeChallenge>>, {data: IssueEmailChangeChallengeRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerIssueEmailChangeChallenge(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerIssueEmailChangeChallengeMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerIssueEmailChangeChallenge>>>
    export type AuthControllerIssueEmailChangeChallengeMutationBody = IssueEmailChangeChallengeRequestDto
    export type AuthControllerIssueEmailChangeChallengeMutationError = unknown

    export const useAuthControllerIssueEmailChangeChallenge = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerIssueEmailChangeChallenge>>, TError,{data: IssueEmailChangeChallengeRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerIssueEmailChangeChallenge>>,
        TError,
        {data: IssueEmailChangeChallengeRequestDto},
        TContext
      > => {
      return useMutation(getAuthControllerIssueEmailChangeChallengeMutationOptions(options), queryClient);
    }
    export const authControllerVerifyEmailChange = (
    verifyEmailChangeRequestDto: VerifyEmailChangeRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerVerifyEmailChange200>(
      {url: `/api/v1/auth/email/change/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyEmailChangeRequestDto, signal
    },
      options);
    }




export const getAuthControllerVerifyEmailChangeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerVerifyEmailChange>>, TError,{data: VerifyEmailChangeRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerVerifyEmailChange>>, TError,{data: VerifyEmailChangeRequestDto}, TContext> => {

const mutationKey = ['authControllerVerifyEmailChange'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerVerifyEmailChange>>, {data: VerifyEmailChangeRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerVerifyEmailChange(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerVerifyEmailChangeMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerVerifyEmailChange>>>
    export type AuthControllerVerifyEmailChangeMutationBody = VerifyEmailChangeRequestDto
    export type AuthControllerVerifyEmailChangeMutationError = unknown

    export const useAuthControllerVerifyEmailChange = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerVerifyEmailChange>>, TError,{data: VerifyEmailChangeRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerVerifyEmailChange>>,
        TError,
        {data: VerifyEmailChangeRequestDto},
        TContext
      > => {
      return useMutation(getAuthControllerVerifyEmailChangeMutationOptions(options), queryClient);
    }
    /**
 * 가입 시 등록된 이름과 휴대폰 번호로 마스킹된 이메일 계정 목록을 조회합니다.
 * @summary 아이디(이메일) 찾기
 */
export const authControllerFindId = (
    findIdRequest: FindIdRequest,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerFindId200>(
      {url: `/api/v1/auth/account/find-id`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: findIdRequest, signal
    },
      options);
    }




export const getAuthControllerFindIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerFindId>>, TError,{data: FindIdRequest}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerFindId>>, TError,{data: FindIdRequest}, TContext> => {

const mutationKey = ['authControllerFindId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerFindId>>, {data: FindIdRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerFindId(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerFindIdMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerFindId>>>
    export type AuthControllerFindIdMutationBody = FindIdRequest
    export type AuthControllerFindIdMutationError = unknown

    /**
 * @summary 아이디(이메일) 찾기
 */
export const useAuthControllerFindId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerFindId>>, TError,{data: FindIdRequest}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerFindId>>,
        TError,
        {data: FindIdRequest},
        TContext
      > => {
      return useMutation(getAuthControllerFindIdMutationOptions(options), queryClient);
    }
    /**
 * 등록된 이메일 계정으로 비밀번호 재설정 링크를 발송합니다.
 * @summary 비밀번호 재설정 인증 메일 발송 요청
 */
export const authControllerIssuePasswordResetChallenge = (
    issuePasswordResetChallengeRequest: IssuePasswordResetChallengeRequest,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerIssuePasswordResetChallenge200>(
      {url: `/api/v1/auth/password/reset/challenge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: issuePasswordResetChallengeRequest, signal
    },
      options);
    }




export const getAuthControllerIssuePasswordResetChallengeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerIssuePasswordResetChallenge>>, TError,{data: IssuePasswordResetChallengeRequest}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerIssuePasswordResetChallenge>>, TError,{data: IssuePasswordResetChallengeRequest}, TContext> => {

const mutationKey = ['authControllerIssuePasswordResetChallenge'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerIssuePasswordResetChallenge>>, {data: IssuePasswordResetChallengeRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerIssuePasswordResetChallenge(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerIssuePasswordResetChallengeMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerIssuePasswordResetChallenge>>>
    export type AuthControllerIssuePasswordResetChallengeMutationBody = IssuePasswordResetChallengeRequest
    export type AuthControllerIssuePasswordResetChallengeMutationError = unknown

    /**
 * @summary 비밀번호 재설정 인증 메일 발송 요청
 */
export const useAuthControllerIssuePasswordResetChallenge = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerIssuePasswordResetChallenge>>, TError,{data: IssuePasswordResetChallengeRequest}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerIssuePasswordResetChallenge>>,
        TError,
        {data: IssuePasswordResetChallengeRequest},
        TContext
      > => {
      return useMutation(getAuthControllerIssuePasswordResetChallengeMutationOptions(options), queryClient);
    }
    /**
 * 재설정 링크의 challengeId와 token의 만료 및 유효 상태를 확인합니다.
 * @summary 비밀번호 재설정 토큰 유효성 검증
 */
export const authControllerVerifyPasswordResetToken = (
    params: AuthControllerVerifyPasswordResetTokenParams,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerVerifyPasswordResetToken200>(
      {url: `/api/v1/auth/password/reset/verify`, method: 'GET',
        params, signal
    },
      options);
    }




export const getAuthControllerVerifyPasswordResetTokenQueryKey = (params?: AuthControllerVerifyPasswordResetTokenParams,) => {
    return [
    `/api/v1/auth/password/reset/verify`, ...(params ? [params] : [])
    ] as const;
    }


export const getAuthControllerVerifyPasswordResetTokenQueryOptions = <TData = Awaited<ReturnType<typeof authControllerVerifyPasswordResetToken>>, TError = unknown>(params: AuthControllerVerifyPasswordResetTokenParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerVerifyPasswordResetToken>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerVerifyPasswordResetTokenQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerVerifyPasswordResetToken>>> = ({ signal }) => authControllerVerifyPasswordResetToken(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerVerifyPasswordResetToken>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerVerifyPasswordResetTokenQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerVerifyPasswordResetToken>>>
export type AuthControllerVerifyPasswordResetTokenQueryError = unknown


export function useAuthControllerVerifyPasswordResetToken<TData = Awaited<ReturnType<typeof authControllerVerifyPasswordResetToken>>, TError = unknown>(
 params: AuthControllerVerifyPasswordResetTokenParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerVerifyPasswordResetToken>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerVerifyPasswordResetToken>>,
          TError,
          Awaited<ReturnType<typeof authControllerVerifyPasswordResetToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerVerifyPasswordResetToken<TData = Awaited<ReturnType<typeof authControllerVerifyPasswordResetToken>>, TError = unknown>(
 params: AuthControllerVerifyPasswordResetTokenParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerVerifyPasswordResetToken>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerVerifyPasswordResetToken>>,
          TError,
          Awaited<ReturnType<typeof authControllerVerifyPasswordResetToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerVerifyPasswordResetToken<TData = Awaited<ReturnType<typeof authControllerVerifyPasswordResetToken>>, TError = unknown>(
 params: AuthControllerVerifyPasswordResetTokenParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerVerifyPasswordResetToken>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 비밀번호 재설정 토큰 유효성 검증
 */

export function useAuthControllerVerifyPasswordResetToken<TData = Awaited<ReturnType<typeof authControllerVerifyPasswordResetToken>>, TError = unknown>(
 params: AuthControllerVerifyPasswordResetTokenParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerVerifyPasswordResetToken>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerVerifyPasswordResetTokenQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * 검증 토큰과 함께 새로운 비밀번호를 설정하고 기존 세션을 모두 파기합니다.
 * @summary 비밀번호 재설정 실행
 */
export const authControllerResetPassword = (
    resetPasswordRequest: ResetPasswordRequest,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<AuthControllerResetPassword200>(
      {url: `/api/v1/auth/password/reset`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetPasswordRequest, signal
    },
      options);
    }




export const getAuthControllerResetPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerResetPassword>>, TError,{data: ResetPasswordRequest}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerResetPassword>>, TError,{data: ResetPasswordRequest}, TContext> => {

const mutationKey = ['authControllerResetPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerResetPassword>>, {data: ResetPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerResetPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerResetPassword>>>
    export type AuthControllerResetPasswordMutationBody = ResetPasswordRequest
    export type AuthControllerResetPasswordMutationError = unknown

    /**
 * @summary 비밀번호 재설정 실행
 */
export const useAuthControllerResetPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerResetPassword>>, TError,{data: ResetPasswordRequest}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerResetPassword>>,
        TError,
        {data: ResetPasswordRequest},
        TContext
      > => {
      return useMutation(getAuthControllerResetPasswordMutationOptions(options), queryClient);
    }
