import { PAGINATION_DEFAULT_LIMIT, PAGINATION_PAGE_SIZE_OPTIONS } from '@pkg/shared/common';

export const DATA_GRID_PAGE_SIZE = PAGINATION_DEFAULT_LIMIT;
export const DATA_GRID_PAGE_SIZES = PAGINATION_PAGE_SIZE_OPTIONS;
