/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CustomersControllerGetMeV1200
} from '../../model';

import { axios } from '../../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 내 고객 프로필 조회
 */
export const customersControllerGetMeV1 = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<CustomersControllerGetMeV1200>(
      {url: `/api/v1/customers/me`, method: 'GET', signal
    },
      options);
    }




export const getCustomersControllerGetMeV1QueryKey = () => {
    return [
    `/api/v1/customers/me`
    ] as const;
    }


export const getCustomersControllerGetMeV1QueryOptions = <TData = Awaited<ReturnType<typeof customersControllerGetMeV1>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerGetMeV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCustomersControllerGetMeV1QueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof customersControllerGetMeV1>>> = ({ signal }) => customersControllerGetMeV1(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof customersControllerGetMeV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CustomersControllerGetMeV1QueryResult = NonNullable<Awaited<ReturnType<typeof customersControllerGetMeV1>>>
export type CustomersControllerGetMeV1QueryError = unknown


export function useCustomersControllerGetMeV1<TData = Awaited<ReturnType<typeof customersControllerGetMeV1>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerGetMeV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof customersControllerGetMeV1>>,
          TError,
          Awaited<ReturnType<typeof customersControllerGetMeV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCustomersControllerGetMeV1<TData = Awaited<ReturnType<typeof customersControllerGetMeV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerGetMeV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof customersControllerGetMeV1>>,
          TError,
          Awaited<ReturnType<typeof customersControllerGetMeV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCustomersControllerGetMeV1<TData = Awaited<ReturnType<typeof customersControllerGetMeV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerGetMeV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내 고객 프로필 조회
 */

export function useCustomersControllerGetMeV1<TData = Awaited<ReturnType<typeof customersControllerGetMeV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerGetMeV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCustomersControllerGetMeV1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






