/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary 서비스 약관 그룹 목록 조회
 */
export const ServiceTermsControllerGroupsV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "isRequired": zod.boolean(),
  "sortOrder": zod.number(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}))
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const serviceTermsControllerCreateGroupV1BodyTitleMax = 255;

export const serviceTermsControllerCreateGroupV1BodyIsRequiredDefault = true;
export const serviceTermsControllerCreateGroupV1BodySortOrderDefault = 0;

export const ServiceTermsControllerCreateGroupV1Body = zod.object({
  "title": zod.string().max(serviceTermsControllerCreateGroupV1BodyTitleMax),
  "isRequired": zod.boolean().default(serviceTermsControllerCreateGroupV1BodyIsRequiredDefault),
  "sortOrder": zod.number().default(serviceTermsControllerCreateGroupV1BodySortOrderDefault)
})

export const ServiceTermsControllerCreateGroupV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "isRequired": zod.boolean(),
  "sortOrder": zod.number(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const ServiceTermsControllerUpdateGroupV1Params = zod.object({
  "id": zod.string()
})

export const serviceTermsControllerUpdateGroupV1BodyTitleMax = 255;

export const serviceTermsControllerUpdateGroupV1BodyIsRequiredDefault = true;
export const serviceTermsControllerUpdateGroupV1BodySortOrderDefault = 0;

export const ServiceTermsControllerUpdateGroupV1Body = zod.object({
  "title": zod.string().max(serviceTermsControllerUpdateGroupV1BodyTitleMax),
  "isRequired": zod.boolean().default(serviceTermsControllerUpdateGroupV1BodyIsRequiredDefault),
  "sortOrder": zod.number().default(serviceTermsControllerUpdateGroupV1BodySortOrderDefault)
})

export const ServiceTermsControllerUpdateGroupV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "isRequired": zod.boolean(),
  "sortOrder": zod.number(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const ServiceTermsControllerDeleteGroupV1Params = zod.object({
  "id": zod.string()
})

export const ServiceTermsControllerDeleteGroupV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "success": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * @summary 서비스 약관 목록 조회
 */
export const serviceTermsControllerListV1QueryPageDefault = 1;
export const serviceTermsControllerListV1QueryLimitDefault = 20;
export const serviceTermsControllerListV1QueryLimitMax = 100;



export const ServiceTermsControllerListV1QueryParams = zod.object({
  "sort": zod.array(zod.string()).optional(),
  "direction": zod.array(zod.enum(['asc', 'desc'])).optional(),
  "search": zod.string().optional(),
  "page": zod.number().default(serviceTermsControllerListV1QueryPageDefault),
  "limit": zod.number().max(serviceTermsControllerListV1QueryLimitMax).default(serviceTermsControllerListV1QueryLimitDefault),
  "groupId": zod.uuid().optional()
})

export const ServiceTermsControllerListV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "page": zod.number(),
  "totalPages": zod.number(),
  "hasNextPage": zod.boolean(),
  "hasPrevPage": zod.boolean(),
  "totalCount": zod.number(),
  "items": zod.array(zod.object({
  "id": zod.string(),
  "groupId": zod.string(),
  "title": zod.string(),
  "version": zod.string(),
  "content": zod.string(),
  "reason": zod.string(),
  "summary": zod.string(),
  "isNoticeRequired": zod.boolean().describe('약관 고지 여부'),
  "isRequired": zod.boolean(),
  "sortOrder": zod.number(),
  "isPublished": zod.boolean(),
  "publishedAt": zod.iso.datetime({"offset":true}).nullable(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}))
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const ServiceTermsControllerCreateV1Body = zod.object({
  "groupId": zod.uuid(),
  "version": zod.string(),
  "content": zod.string(),
  "reason": zod.string(),
  "summary": zod.string(),
  "isNoticeRequired": zod.boolean().describe('약관 고지 여부'),
  "publishedAt": zod.iso.datetime({"offset":true}).nullish().describe('게시 예정 시각 (null이면 예약 취소)')
})

export const ServiceTermsControllerCreateV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "id": zod.string(),
  "groupId": zod.string(),
  "title": zod.string(),
  "version": zod.string(),
  "content": zod.string(),
  "reason": zod.string(),
  "summary": zod.string(),
  "isNoticeRequired": zod.boolean().describe('약관 고지 여부'),
  "isRequired": zod.boolean(),
  "sortOrder": zod.number(),
  "isPublished": zod.boolean(),
  "publishedAt": zod.iso.datetime({"offset":true}).nullable(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const ServiceTermsControllerUpdateV1Params = zod.object({
  "id": zod.string()
})

export const ServiceTermsControllerUpdateV1Body = zod.object({
  "groupId": zod.uuid(),
  "version": zod.string(),
  "content": zod.string(),
  "reason": zod.string(),
  "summary": zod.string(),
  "isNoticeRequired": zod.boolean().describe('약관 고지 여부'),
  "publishedAt": zod.iso.datetime({"offset":true}).nullish().describe('게시 예정 시각 (null이면 예약 취소)')
})

export const ServiceTermsControllerUpdateV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "id": zod.string(),
  "groupId": zod.string(),
  "title": zod.string(),
  "version": zod.string(),
  "content": zod.string(),
  "reason": zod.string(),
  "summary": zod.string(),
  "isNoticeRequired": zod.boolean().describe('약관 고지 여부'),
  "isRequired": zod.boolean(),
  "sortOrder": zod.number(),
  "isPublished": zod.boolean(),
  "publishedAt": zod.iso.datetime({"offset":true}).nullable(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const ServiceTermsControllerDeleteV1Params = zod.object({
  "id": zod.string()
})

export const ServiceTermsControllerDeleteV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "success": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const ServiceTermsControllerPublishV1Params = zod.object({
  "id": zod.string()
})

export const ServiceTermsControllerPublishV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "id": zod.string(),
  "groupId": zod.string(),
  "title": zod.string(),
  "version": zod.string(),
  "content": zod.string(),
  "reason": zod.string(),
  "summary": zod.string(),
  "isNoticeRequired": zod.boolean().describe('약관 고지 여부'),
  "isRequired": zod.boolean(),
  "sortOrder": zod.number(),
  "isPublished": zod.boolean(),
  "publishedAt": zod.iso.datetime({"offset":true}).nullable(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

