/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const PermissionsControllerGetPermissionsV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "code": zod.string(),
  "resource": zod.string(),
  "action": zod.string(),
  "label": zod.string(),
  "description": zod.looseObject({

}).nullable()
}))
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

