/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary 관리자 목록 조회
 */
export const usersControllerGetUsersV1QueryPageDefault = 1;
export const usersControllerGetUsersV1QueryLimitDefault = 20;
export const usersControllerGetUsersV1QueryLimitMax = 100;

export const usersControllerGetUsersV1QueryIncludeDeletedDefault = false;

export const UsersControllerGetUsersV1QueryParams = zod.object({
  "sort": zod.array(zod.string()).optional(),
  "direction": zod.array(zod.enum(['asc', 'desc'])).optional(),
  "search": zod.string().optional(),
  "page": zod.number().default(usersControllerGetUsersV1QueryPageDefault),
  "limit": zod.number().max(usersControllerGetUsersV1QueryLimitMax).default(usersControllerGetUsersV1QueryLimitDefault),
  "includeDeleted": zod.boolean().default(usersControllerGetUsersV1QueryIncludeDeletedDefault),
  "status": zod.enum(['active', 'banned', 'deleted']).optional(),
  "twoFactorEnabled": zod.boolean().optional()
})

export const UsersControllerGetUsersV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "page": zod.number(),
  "totalPages": zod.number(),
  "hasNextPage": zod.boolean(),
  "hasPrevPage": zod.boolean(),
  "totalCount": zod.number(),
  "items": zod.array(zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "roleCode": zod.string().describe('할당된 역할 코드'),
  "roleLabel": zod.string().describe('할당된 역할 표시명'),
  "twoFactorEnabled": zod.boolean(),
  "banned": zod.boolean(),
  "banReason": zod.string().nullish(),
  "banExpires": zod.iso.datetime({"offset":true}).nullish(),
  "deleted": zod.boolean(),
  "deletedAt": zod.iso.datetime({"offset":true}).nullish(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}))
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * @summary 관리자 생성
 */
export const usersControllerCreateUserV1BodyNameMax = 120;

export const usersControllerCreateUserV1BodyEmailMax = 320;

export const usersControllerCreateUserV1BodyPasswordMin = 8;

export const usersControllerCreateUserV1BodyRoleDefault = `admin`;

export const UsersControllerCreateUserV1Body = zod.object({
  "name": zod.string().max(usersControllerCreateUserV1BodyNameMax),
  "email": zod.email().max(usersControllerCreateUserV1BodyEmailMax),
  "password": zod.string().min(usersControllerCreateUserV1BodyPasswordMin).describe('초기 비밀번호'),
  "role": zod.string().default(usersControllerCreateUserV1BodyRoleDefault)
})

export const UsersControllerCreateUserV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "id": zod.string()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * @summary 관리자 현황 조회
 */
export const UsersControllerGetUserOverviewV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "totalUsers": zod.number(),
  "activeUsers": zod.number(),
  "bannedUsers": zod.number(),
  "deletedUsers": zod.number(),
  "twoFactorEnabledUsers": zod.number()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * @summary 관리자 상세 조회
 */
export const UsersControllerGetUserByIdV1Params = zod.object({
  "id": zod.string()
})

export const UsersControllerGetUserByIdV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "roleCode": zod.string().describe('할당된 역할 코드'),
  "roleLabel": zod.string().describe('할당된 역할 표시명'),
  "twoFactorEnabled": zod.boolean(),
  "banned": zod.boolean(),
  "banReason": zod.string().nullish(),
  "banExpires": zod.iso.datetime({"offset":true}).nullish(),
  "deleted": zod.boolean(),
  "deletedAt": zod.iso.datetime({"offset":true}).nullish(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "providers": zod.array(zod.string()),
  "hasPassword": zod.boolean(),
  "passwordUpdatedAt": zod.iso.datetime({"offset":true}).nullish(),
  "lastLoginAt": zod.iso.datetime({"offset":true}).nullish()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * @summary 관리자 삭제
 */
export const UsersControllerDeleteUserV1Params = zod.object({
  "id": zod.string()
})

export const UsersControllerDeleteUserV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.looseObject({

}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * @summary 관리자 이용 정지
 */
export const UsersControllerBanUserV1Params = zod.object({
  "id": zod.string()
})

export const usersControllerBanUserV1BodyReasonMax = 255;



export const UsersControllerBanUserV1Body = zod.object({
  "reason": zod.string().max(usersControllerBanUserV1BodyReasonMax).optional(),
  "expiresAt": zod.iso.datetime({"offset":true}).optional().describe('미입력 시 무기한 정지')
})

export const UsersControllerBanUserV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.looseObject({

}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * @summary 관리자 이용 정지 해제
 */
export const UsersControllerUnbanUserV1Params = zod.object({
  "id": zod.string()
})

export const UsersControllerUnbanUserV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.looseObject({

}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * @summary 관리자 복구
 */
export const UsersControllerRestoreUserV1Params = zod.object({
  "id": zod.string()
})

export const UsersControllerRestoreUserV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.looseObject({

}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * @summary 관리자 역할 변경
 */
export const UsersControllerUpdateUserRoleV1Params = zod.object({
  "id": zod.string()
})

export const UsersControllerUpdateUserRoleV1Body = zod.object({
  "role": zod.string()
})

export const UsersControllerUpdateUserRoleV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.looseObject({

}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * @summary 관리자 2단계 인증 초기화
 */
export const UsersControllerResetUserTwoFactorV1Params = zod.object({
  "id": zod.string()
})

export const UsersControllerResetUserTwoFactorV1Response = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.looseObject({

}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})
