/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateNoticeRequestDto,
  NoticesControllerCreateNotice201,
  NoticesControllerDeleteNotice200,
  NoticesControllerGetAdminNotice200,
  NoticesControllerGetAdminNotices200,
  NoticesControllerGetAdminNoticesParams,
  NoticesControllerGetNoticeFeed200,
  NoticesControllerGetNoticeFeedParams,
  NoticesControllerGetNotices200,
  NoticesControllerMarkAllAsRead200,
  NoticesControllerMarkAsRead200,
  NoticesControllerUpdateNotice200,
  UpdateNoticeRequestDto
} from '../../model';

import { axios } from '../../../../core/config/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const noticesControllerGetNotices = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<NoticesControllerGetNotices200>(
      {url: `/api/v1/notices`, method: 'GET', signal
    },
      options);
    }




export const getNoticesControllerGetNoticesQueryKey = () => {
    return [
    `/api/v1/notices`
    ] as const;
    }


export const getNoticesControllerGetNoticesQueryOptions = <TData = Awaited<ReturnType<typeof noticesControllerGetNotices>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetNotices>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNoticesControllerGetNoticesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof noticesControllerGetNotices>>> = ({ signal }) => noticesControllerGetNotices(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetNotices>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NoticesControllerGetNoticesQueryResult = NonNullable<Awaited<ReturnType<typeof noticesControllerGetNotices>>>
export type NoticesControllerGetNoticesQueryError = unknown


export function useNoticesControllerGetNotices<TData = Awaited<ReturnType<typeof noticesControllerGetNotices>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetNotices>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof noticesControllerGetNotices>>,
          TError,
          Awaited<ReturnType<typeof noticesControllerGetNotices>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNoticesControllerGetNotices<TData = Awaited<ReturnType<typeof noticesControllerGetNotices>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetNotices>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof noticesControllerGetNotices>>,
          TError,
          Awaited<ReturnType<typeof noticesControllerGetNotices>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNoticesControllerGetNotices<TData = Awaited<ReturnType<typeof noticesControllerGetNotices>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetNotices>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNoticesControllerGetNotices<TData = Awaited<ReturnType<typeof noticesControllerGetNotices>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetNotices>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNoticesControllerGetNoticesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const noticesControllerGetNoticeFeed = (
    params?: NoticesControllerGetNoticeFeedParams,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<NoticesControllerGetNoticeFeed200>(
      {url: `/api/v1/notices/feed`, method: 'GET',
        params, signal
    },
      options);
    }




export const getNoticesControllerGetNoticeFeedQueryKey = (params?: NoticesControllerGetNoticeFeedParams,) => {
    return [
    `/api/v1/notices/feed`, ...(params ? [params] : [])
    ] as const;
    }


export const getNoticesControllerGetNoticeFeedQueryOptions = <TData = Awaited<ReturnType<typeof noticesControllerGetNoticeFeed>>, TError = unknown>(params?: NoticesControllerGetNoticeFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetNoticeFeed>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNoticesControllerGetNoticeFeedQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof noticesControllerGetNoticeFeed>>> = ({ signal }) => noticesControllerGetNoticeFeed(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetNoticeFeed>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NoticesControllerGetNoticeFeedQueryResult = NonNullable<Awaited<ReturnType<typeof noticesControllerGetNoticeFeed>>>
export type NoticesControllerGetNoticeFeedQueryError = unknown


export function useNoticesControllerGetNoticeFeed<TData = Awaited<ReturnType<typeof noticesControllerGetNoticeFeed>>, TError = unknown>(
 params: undefined |  NoticesControllerGetNoticeFeedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetNoticeFeed>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof noticesControllerGetNoticeFeed>>,
          TError,
          Awaited<ReturnType<typeof noticesControllerGetNoticeFeed>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNoticesControllerGetNoticeFeed<TData = Awaited<ReturnType<typeof noticesControllerGetNoticeFeed>>, TError = unknown>(
 params?: NoticesControllerGetNoticeFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetNoticeFeed>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof noticesControllerGetNoticeFeed>>,
          TError,
          Awaited<ReturnType<typeof noticesControllerGetNoticeFeed>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNoticesControllerGetNoticeFeed<TData = Awaited<ReturnType<typeof noticesControllerGetNoticeFeed>>, TError = unknown>(
 params?: NoticesControllerGetNoticeFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetNoticeFeed>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNoticesControllerGetNoticeFeed<TData = Awaited<ReturnType<typeof noticesControllerGetNoticeFeed>>, TError = unknown>(
 params?: NoticesControllerGetNoticeFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetNoticeFeed>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNoticesControllerGetNoticeFeedQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const noticesControllerMarkAllAsRead = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<NoticesControllerMarkAllAsRead200>(
      {url: `/api/v1/notices/read-all`, method: 'POST', signal
    },
      options);
    }




export const getNoticesControllerMarkAllAsReadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof noticesControllerMarkAllAsRead>>, TError,void, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof noticesControllerMarkAllAsRead>>, TError,void, TContext> => {

const mutationKey = ['noticesControllerMarkAllAsRead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof noticesControllerMarkAllAsRead>>, void> = () => {


          return  noticesControllerMarkAllAsRead(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NoticesControllerMarkAllAsReadMutationResult = NonNullable<Awaited<ReturnType<typeof noticesControllerMarkAllAsRead>>>

    export type NoticesControllerMarkAllAsReadMutationError = unknown

    export const useNoticesControllerMarkAllAsRead = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof noticesControllerMarkAllAsRead>>, TError,void, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof noticesControllerMarkAllAsRead>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getNoticesControllerMarkAllAsReadMutationOptions(options), queryClient);
    }
    export const noticesControllerMarkAsRead = (
    id: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<NoticesControllerMarkAsRead200>(
      {url: `/api/v1/notices/${id}/read`, method: 'POST', signal
    },
      options);
    }




export const getNoticesControllerMarkAsReadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof noticesControllerMarkAsRead>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof noticesControllerMarkAsRead>>, TError,{id: string}, TContext> => {

const mutationKey = ['noticesControllerMarkAsRead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof noticesControllerMarkAsRead>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  noticesControllerMarkAsRead(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NoticesControllerMarkAsReadMutationResult = NonNullable<Awaited<ReturnType<typeof noticesControllerMarkAsRead>>>

    export type NoticesControllerMarkAsReadMutationError = unknown

    export const useNoticesControllerMarkAsRead = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof noticesControllerMarkAsRead>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof noticesControllerMarkAsRead>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getNoticesControllerMarkAsReadMutationOptions(options), queryClient);
    }
    export const noticesControllerGetAdminNotices = (
    params?: NoticesControllerGetAdminNoticesParams,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<NoticesControllerGetAdminNotices200>(
      {url: `/api/v1/notices/admin`, method: 'GET',
        params, signal
    },
      options);
    }




export const getNoticesControllerGetAdminNoticesQueryKey = (params?: NoticesControllerGetAdminNoticesParams,) => {
    return [
    `/api/v1/notices/admin`, ...(params ? [params] : [])
    ] as const;
    }


export const getNoticesControllerGetAdminNoticesQueryOptions = <TData = Awaited<ReturnType<typeof noticesControllerGetAdminNotices>>, TError = unknown>(params?: NoticesControllerGetAdminNoticesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetAdminNotices>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNoticesControllerGetAdminNoticesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof noticesControllerGetAdminNotices>>> = ({ signal }) => noticesControllerGetAdminNotices(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetAdminNotices>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NoticesControllerGetAdminNoticesQueryResult = NonNullable<Awaited<ReturnType<typeof noticesControllerGetAdminNotices>>>
export type NoticesControllerGetAdminNoticesQueryError = unknown


export function useNoticesControllerGetAdminNotices<TData = Awaited<ReturnType<typeof noticesControllerGetAdminNotices>>, TError = unknown>(
 params: undefined |  NoticesControllerGetAdminNoticesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetAdminNotices>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof noticesControllerGetAdminNotices>>,
          TError,
          Awaited<ReturnType<typeof noticesControllerGetAdminNotices>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNoticesControllerGetAdminNotices<TData = Awaited<ReturnType<typeof noticesControllerGetAdminNotices>>, TError = unknown>(
 params?: NoticesControllerGetAdminNoticesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetAdminNotices>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof noticesControllerGetAdminNotices>>,
          TError,
          Awaited<ReturnType<typeof noticesControllerGetAdminNotices>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNoticesControllerGetAdminNotices<TData = Awaited<ReturnType<typeof noticesControllerGetAdminNotices>>, TError = unknown>(
 params?: NoticesControllerGetAdminNoticesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetAdminNotices>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNoticesControllerGetAdminNotices<TData = Awaited<ReturnType<typeof noticesControllerGetAdminNotices>>, TError = unknown>(
 params?: NoticesControllerGetAdminNoticesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetAdminNotices>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNoticesControllerGetAdminNoticesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const noticesControllerCreateNotice = (
    createNoticeRequestDto: CreateNoticeRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<NoticesControllerCreateNotice201>(
      {url: `/api/v1/notices/admin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createNoticeRequestDto, signal
    },
      options);
    }




export const getNoticesControllerCreateNoticeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof noticesControllerCreateNotice>>, TError,{data: CreateNoticeRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof noticesControllerCreateNotice>>, TError,{data: CreateNoticeRequestDto}, TContext> => {

const mutationKey = ['noticesControllerCreateNotice'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof noticesControllerCreateNotice>>, {data: CreateNoticeRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  noticesControllerCreateNotice(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NoticesControllerCreateNoticeMutationResult = NonNullable<Awaited<ReturnType<typeof noticesControllerCreateNotice>>>
    export type NoticesControllerCreateNoticeMutationBody = CreateNoticeRequestDto
    export type NoticesControllerCreateNoticeMutationError = unknown

    export const useNoticesControllerCreateNotice = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof noticesControllerCreateNotice>>, TError,{data: CreateNoticeRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof noticesControllerCreateNotice>>,
        TError,
        {data: CreateNoticeRequestDto},
        TContext
      > => {
      return useMutation(getNoticesControllerCreateNoticeMutationOptions(options), queryClient);
    }
    export const noticesControllerGetAdminNotice = (
    id: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<NoticesControllerGetAdminNotice200>(
      {url: `/api/v1/notices/admin/${id}`, method: 'GET', signal
    },
      options);
    }




export const getNoticesControllerGetAdminNoticeQueryKey = (id: string,) => {
    return [
    `/api/v1/notices/admin/${id}`
    ] as const;
    }


export const getNoticesControllerGetAdminNoticeQueryOptions = <TData = Awaited<ReturnType<typeof noticesControllerGetAdminNotice>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetAdminNotice>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNoticesControllerGetAdminNoticeQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof noticesControllerGetAdminNotice>>> = ({ signal }) => noticesControllerGetAdminNotice(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetAdminNotice>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NoticesControllerGetAdminNoticeQueryResult = NonNullable<Awaited<ReturnType<typeof noticesControllerGetAdminNotice>>>
export type NoticesControllerGetAdminNoticeQueryError = unknown


export function useNoticesControllerGetAdminNotice<TData = Awaited<ReturnType<typeof noticesControllerGetAdminNotice>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetAdminNotice>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof noticesControllerGetAdminNotice>>,
          TError,
          Awaited<ReturnType<typeof noticesControllerGetAdminNotice>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNoticesControllerGetAdminNotice<TData = Awaited<ReturnType<typeof noticesControllerGetAdminNotice>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetAdminNotice>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof noticesControllerGetAdminNotice>>,
          TError,
          Awaited<ReturnType<typeof noticesControllerGetAdminNotice>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNoticesControllerGetAdminNotice<TData = Awaited<ReturnType<typeof noticesControllerGetAdminNotice>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetAdminNotice>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNoticesControllerGetAdminNotice<TData = Awaited<ReturnType<typeof noticesControllerGetAdminNotice>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticesControllerGetAdminNotice>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNoticesControllerGetAdminNoticeQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const noticesControllerUpdateNotice = (
    id: string,
    updateNoticeRequestDto: UpdateNoticeRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<NoticesControllerUpdateNotice200>(
      {url: `/api/v1/notices/admin/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateNoticeRequestDto, signal
    },
      options);
    }




export const getNoticesControllerUpdateNoticeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof noticesControllerUpdateNotice>>, TError,{id: string;data: UpdateNoticeRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof noticesControllerUpdateNotice>>, TError,{id: string;data: UpdateNoticeRequestDto}, TContext> => {

const mutationKey = ['noticesControllerUpdateNotice'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof noticesControllerUpdateNotice>>, {id: string;data: UpdateNoticeRequestDto}> = (props) => {
          const {id,data} = props ?? {};

          return  noticesControllerUpdateNotice(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NoticesControllerUpdateNoticeMutationResult = NonNullable<Awaited<ReturnType<typeof noticesControllerUpdateNotice>>>
    export type NoticesControllerUpdateNoticeMutationBody = UpdateNoticeRequestDto
    export type NoticesControllerUpdateNoticeMutationError = unknown

    export const useNoticesControllerUpdateNotice = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof noticesControllerUpdateNotice>>, TError,{id: string;data: UpdateNoticeRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof noticesControllerUpdateNotice>>,
        TError,
        {id: string;data: UpdateNoticeRequestDto},
        TContext
      > => {
      return useMutation(getNoticesControllerUpdateNoticeMutationOptions(options), queryClient);
    }
    export const noticesControllerDeleteNotice = (
    id: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<NoticesControllerDeleteNotice200>(
      {url: `/api/v1/notices/admin/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getNoticesControllerDeleteNoticeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof noticesControllerDeleteNotice>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof noticesControllerDeleteNotice>>, TError,{id: string}, TContext> => {

const mutationKey = ['noticesControllerDeleteNotice'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof noticesControllerDeleteNotice>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  noticesControllerDeleteNotice(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NoticesControllerDeleteNoticeMutationResult = NonNullable<Awaited<ReturnType<typeof noticesControllerDeleteNotice>>>

    export type NoticesControllerDeleteNoticeMutationError = unknown

    export const useNoticesControllerDeleteNotice = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof noticesControllerDeleteNotice>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof noticesControllerDeleteNotice>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getNoticesControllerDeleteNoticeMutationOptions(options), queryClient);
    }
