/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ResourcesControllerGetResources200
} from '../../model';

import { axios } from '../../../../core/config/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const resourcesControllerGetResources = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<ResourcesControllerGetResources200>(
      {url: `/api/v1/resources`, method: 'GET', signal
    },
      options);
    }




export const getResourcesControllerGetResourcesQueryKey = () => {
    return [
    `/api/v1/resources`
    ] as const;
    }


export const getResourcesControllerGetResourcesQueryOptions = <TData = Awaited<ReturnType<typeof resourcesControllerGetResources>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resourcesControllerGetResources>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getResourcesControllerGetResourcesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof resourcesControllerGetResources>>> = ({ signal }) => resourcesControllerGetResources(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof resourcesControllerGetResources>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ResourcesControllerGetResourcesQueryResult = NonNullable<Awaited<ReturnType<typeof resourcesControllerGetResources>>>
export type ResourcesControllerGetResourcesQueryError = unknown


export function useResourcesControllerGetResources<TData = Awaited<ReturnType<typeof resourcesControllerGetResources>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof resourcesControllerGetResources>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resourcesControllerGetResources>>,
          TError,
          Awaited<ReturnType<typeof resourcesControllerGetResources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResourcesControllerGetResources<TData = Awaited<ReturnType<typeof resourcesControllerGetResources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resourcesControllerGetResources>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resourcesControllerGetResources>>,
          TError,
          Awaited<ReturnType<typeof resourcesControllerGetResources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResourcesControllerGetResources<TData = Awaited<ReturnType<typeof resourcesControllerGetResources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resourcesControllerGetResources>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useResourcesControllerGetResources<TData = Awaited<ReturnType<typeof resourcesControllerGetResources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resourcesControllerGetResources>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getResourcesControllerGetResourcesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






