/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateFaqRequest,
  FaqsControllerCreateFaqV1201,
  FaqsControllerDeleteFaqV1200,
  FaqsControllerListFaqsV1200,
  FaqsControllerListFaqsV1Params,
  FaqsControllerUpdateFaqV1200,
  UpdateFaqRequestDto
} from '../../model';

import { axios } from '../../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary FAQ 목록 조회
 */
export const faqsControllerListFaqsV1 = (
    params?: FaqsControllerListFaqsV1Params,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<FaqsControllerListFaqsV1200>(
      {url: `/api/v1/faqs`, method: 'GET',
        params, signal
    },
      options);
    }




export const getFaqsControllerListFaqsV1QueryKey = (params?: FaqsControllerListFaqsV1Params,) => {
    return [
    `/api/v1/faqs`, ...(params ? [params] : [])
    ] as const;
    }


export const getFaqsControllerListFaqsV1QueryOptions = <TData = Awaited<ReturnType<typeof faqsControllerListFaqsV1>>, TError = unknown>(params?: FaqsControllerListFaqsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof faqsControllerListFaqsV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFaqsControllerListFaqsV1QueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof faqsControllerListFaqsV1>>> = ({ signal }) => faqsControllerListFaqsV1(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof faqsControllerListFaqsV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FaqsControllerListFaqsV1QueryResult = NonNullable<Awaited<ReturnType<typeof faqsControllerListFaqsV1>>>
export type FaqsControllerListFaqsV1QueryError = unknown


export function useFaqsControllerListFaqsV1<TData = Awaited<ReturnType<typeof faqsControllerListFaqsV1>>, TError = unknown>(
 params: undefined |  FaqsControllerListFaqsV1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof faqsControllerListFaqsV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof faqsControllerListFaqsV1>>,
          TError,
          Awaited<ReturnType<typeof faqsControllerListFaqsV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFaqsControllerListFaqsV1<TData = Awaited<ReturnType<typeof faqsControllerListFaqsV1>>, TError = unknown>(
 params?: FaqsControllerListFaqsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof faqsControllerListFaqsV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof faqsControllerListFaqsV1>>,
          TError,
          Awaited<ReturnType<typeof faqsControllerListFaqsV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFaqsControllerListFaqsV1<TData = Awaited<ReturnType<typeof faqsControllerListFaqsV1>>, TError = unknown>(
 params?: FaqsControllerListFaqsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof faqsControllerListFaqsV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary FAQ 목록 조회
 */

export function useFaqsControllerListFaqsV1<TData = Awaited<ReturnType<typeof faqsControllerListFaqsV1>>, TError = unknown>(
 params?: FaqsControllerListFaqsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof faqsControllerListFaqsV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFaqsControllerListFaqsV1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const faqsControllerCreateFaqV1 = (
    createFaqRequest: CreateFaqRequest,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<FaqsControllerCreateFaqV1201>(
      {url: `/api/v1/faqs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFaqRequest, signal
    },
      options);
    }




export const getFaqsControllerCreateFaqV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof faqsControllerCreateFaqV1>>, TError,{data: CreateFaqRequest}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof faqsControllerCreateFaqV1>>, TError,{data: CreateFaqRequest}, TContext> => {

const mutationKey = ['faqsControllerCreateFaqV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof faqsControllerCreateFaqV1>>, {data: CreateFaqRequest}> = (props) => {
          const {data} = props ?? {};

          return  faqsControllerCreateFaqV1(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FaqsControllerCreateFaqV1MutationResult = NonNullable<Awaited<ReturnType<typeof faqsControllerCreateFaqV1>>>
    export type FaqsControllerCreateFaqV1MutationBody = CreateFaqRequest
    export type FaqsControllerCreateFaqV1MutationError = unknown

    export const useFaqsControllerCreateFaqV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof faqsControllerCreateFaqV1>>, TError,{data: CreateFaqRequest}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof faqsControllerCreateFaqV1>>,
        TError,
        {data: CreateFaqRequest},
        TContext
      > => {
      return useMutation(getFaqsControllerCreateFaqV1MutationOptions(options), queryClient);
    }
    export const faqsControllerUpdateFaqV1 = (
    id: string,
    updateFaqRequestDto: UpdateFaqRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<FaqsControllerUpdateFaqV1200>(
      {url: `/api/v1/faqs/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateFaqRequestDto, signal
    },
      options);
    }




export const getFaqsControllerUpdateFaqV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof faqsControllerUpdateFaqV1>>, TError,{id: string;data: UpdateFaqRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof faqsControllerUpdateFaqV1>>, TError,{id: string;data: UpdateFaqRequestDto}, TContext> => {

const mutationKey = ['faqsControllerUpdateFaqV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof faqsControllerUpdateFaqV1>>, {id: string;data: UpdateFaqRequestDto}> = (props) => {
          const {id,data} = props ?? {};

          return  faqsControllerUpdateFaqV1(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FaqsControllerUpdateFaqV1MutationResult = NonNullable<Awaited<ReturnType<typeof faqsControllerUpdateFaqV1>>>
    export type FaqsControllerUpdateFaqV1MutationBody = UpdateFaqRequestDto
    export type FaqsControllerUpdateFaqV1MutationError = unknown

    export const useFaqsControllerUpdateFaqV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof faqsControllerUpdateFaqV1>>, TError,{id: string;data: UpdateFaqRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof faqsControllerUpdateFaqV1>>,
        TError,
        {id: string;data: UpdateFaqRequestDto},
        TContext
      > => {
      return useMutation(getFaqsControllerUpdateFaqV1MutationOptions(options), queryClient);
    }
    export const faqsControllerDeleteFaqV1 = (
    id: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<FaqsControllerDeleteFaqV1200>(
      {url: `/api/v1/faqs/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getFaqsControllerDeleteFaqV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof faqsControllerDeleteFaqV1>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof faqsControllerDeleteFaqV1>>, TError,{id: string}, TContext> => {

const mutationKey = ['faqsControllerDeleteFaqV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof faqsControllerDeleteFaqV1>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  faqsControllerDeleteFaqV1(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FaqsControllerDeleteFaqV1MutationResult = NonNullable<Awaited<ReturnType<typeof faqsControllerDeleteFaqV1>>>

    export type FaqsControllerDeleteFaqV1MutationError = unknown

    export const useFaqsControllerDeleteFaqV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof faqsControllerDeleteFaqV1>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof faqsControllerDeleteFaqV1>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getFaqsControllerDeleteFaqV1MutationOptions(options), queryClient);
    }
