/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const AuthControllerGetCsrfTokenResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const authControllerUserRegisterBodyPasswordMin = 10;
export const authControllerUserRegisterBodyPasswordMax = 24;

export const authControllerUserRegisterBodyNameMax = 120;



export const AuthControllerUserRegisterBody = zod.object({
  "email": zod.email(),
  "password": zod.string().min(authControllerUserRegisterBodyPasswordMin).max(authControllerUserRegisterBodyPasswordMax),
  "name": zod.string().min(1).max(authControllerUserRegisterBodyNameMax)
})

export const AuthControllerUserRegisterResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const authControllerLoginCredentialBodyPasswordMin = 10;
export const authControllerLoginCredentialBodyPasswordMax = 24;



export const AuthControllerLoginCredentialBody = zod.object({
  "email": zod.email(),
  "password": zod.string().min(authControllerLoginCredentialBodyPasswordMin).max(authControllerLoginCredentialBodyPasswordMax)
})

export const AuthControllerLoginCredentialResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean(),
  "twoFactorRedirect": zod.boolean().optional()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerGoogleAuthResponse = zod.void()

export const AuthControllerGoogleAuthRedirectResponse = zod.void()

export const authControllerUserProfileResponseDataUserNameMax = 120;



export const AuthControllerUserProfileResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "user": zod.object({
  "id": zod.uuid(),
  "name": zod.string().max(authControllerUserProfileResponseDataUserNameMax),
  "email": zod.email(),
  "emailVerified": zod.boolean(),
  "image": zod.string().nullish(),
  "twoFactorEnabled": zod.boolean(),
  "banned": zod.boolean(),
  "banReason": zod.string().nullish(),
  "banExpires": zod.iso.datetime({"offset":true}).nullish(),
  "role": zod.enum(['user']).nullable(),
  "permissions": zod.record(zod.string(), zod.array(zod.string())),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "passwordUpdatedAt": zod.iso.datetime({"offset":true}).nullish(),
  "isPasswordChangeRequired": zod.boolean()
}),
  "expiresAt": zod.iso.datetime({"offset":true}).nullable()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerAccountLinkBody = zod.object({
  "providerId": zod.string(),
  "accountId": zod.string(),
  "accessToken": zod.looseObject({

}).optional(),
  "refreshToken": zod.looseObject({

}).optional()
})

export const AuthControllerAccountLinkResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const authControllerStopImpersonatingResponseDataUserNameMax = 120;



export const AuthControllerStopImpersonatingResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "user": zod.object({
  "id": zod.uuid(),
  "name": zod.string().max(authControllerStopImpersonatingResponseDataUserNameMax),
  "email": zod.email(),
  "emailVerified": zod.boolean(),
  "image": zod.string().nullish(),
  "twoFactorEnabled": zod.boolean(),
  "banned": zod.boolean(),
  "banReason": zod.string().nullish(),
  "banExpires": zod.iso.datetime({"offset":true}).nullish(),
  "role": zod.enum(['user']).nullable(),
  "permissions": zod.record(zod.string(), zod.array(zod.string())),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "passwordUpdatedAt": zod.iso.datetime({"offset":true}).nullish(),
  "isPasswordChangeRequired": zod.boolean()
}),
  "expiresAt": zod.iso.datetime({"offset":true}).nullable()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerAccountUnlinkBody = zod.object({
  "providerId": zod.string(),
  "accountId": zod.string()
})

export const AuthControllerAccountUnlinkResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerUserUnregisterResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerLogoutResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerGenerate2FAResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "url": zod.string().describe('QR Code Data URL')
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerTurnOn2FABody = zod.object({
  "code": zod.string().describe('The 6-digit 2FA code generated by the authenticator app')
})

export const AuthControllerTurnOn2FAResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerTurnOff2FAResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerVerify2FAChallengeBody = zod.object({
  "code": zod.string().describe('The 6-digit 2FA code generated by the authenticator app')
})

export const AuthControllerVerify2FAChallengeResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const authControllerChangePasswordBodyNewPasswordMin = 10;
export const authControllerChangePasswordBodyNewPasswordMax = 24;



export const AuthControllerChangePasswordBody = zod.object({
  "currentPassword": zod.string(),
  "newPassword": zod.string().min(authControllerChangePasswordBodyNewPasswordMin).max(authControllerChangePasswordBodyNewPasswordMax),
  "confirmPassword": zod.string()
})

export const AuthControllerChangePasswordResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerDeferPasswordChangeResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

