/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const AuthControllerGoogleLoginResponse = zod.unknown()

export const authControllerLoginBodyPasswordMin = 10;
export const authControllerLoginBodyPasswordMax = 24;

export const authControllerLoginBodyRememberMeDefault = false;

export const AuthControllerLoginBody = zod.object({
  "email": zod.email(),
  "password": zod.string().min(authControllerLoginBodyPasswordMin).max(authControllerLoginBodyPasswordMax),
  "rememberMe": zod.boolean().default(authControllerLoginBodyRememberMeDefault).describe('로그인 상태 유지 (자동 로그인)')
})

export const AuthControllerLoginResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "challengeId": zod.string().optional(),
  "expiresIn": zod.number().optional(),
  "ok": zod.boolean().optional()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const authControllerRegisterBodyPasswordMin = 10;
export const authControllerRegisterBodyPasswordMax = 24;

export const authControllerRegisterBodyNameMax = 120;



export const AuthControllerRegisterBody = zod.object({
  "email": zod.email(),
  "password": zod.string().min(authControllerRegisterBodyPasswordMin).max(authControllerRegisterBodyPasswordMax),
  "name": zod.string().min(1).max(authControllerRegisterBodyNameMax)
})

export const AuthControllerRegisterResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerGoogleCallbackQueryParams = zod.object({
  "code": zod.string().optional(),
  "state": zod.string().optional(),
  "error": zod.string().optional(),
  "error_description": zod.string().optional(),
  "iss": zod.string().optional(),
  "scope": zod.string().optional(),
  "authuser": zod.string().optional(),
  "prompt": zod.string().optional()
})

export const AuthControllerGoogleCallbackResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "challengeId": zod.string().optional(),
  "expiresIn": zod.number().optional(),
  "ok": zod.boolean().optional()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerVerify2FAChallengeBody = zod.object({
  "challengeId": zod.string(),
  "code": zod.string()
})

export const AuthControllerVerify2FAChallengeResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerLogoutResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerSyncAnalyticsConsentBody = zod.looseObject({

})

export const AuthControllerSyncAnalyticsConsentResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const authControllerUserProfileResponseDataNameMax = 120;



export const AuthControllerUserProfileResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "id": zod.uuid(),
  "name": zod.string().max(authControllerUserProfileResponseDataNameMax),
  "email": zod.email(),
  "emailVerified": zod.boolean(),
  "phoneNumber": zod.string().nullable(),
  "phoneNumberVerified": zod.boolean(),
  "role": zod.enum(['user', 'admin']).nullable(),
  "permissions": zod.record(zod.string(), zod.array(zod.string())),
  "requiredTermsAgreed": zod.boolean(),
  "passwordUpdatedAt": zod.iso.datetime({"offset":true}).nullable(),
  "isPasswordChangeRequired": zod.boolean(),
  "twoFactorEnabled": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerAccountLinkBody = zod.object({
  "providerId": zod.enum(['google', 'kakao', 'naver', 'github']),
  "accountId": zod.string(),
  "accessToken": zod.string().nullish(),
  "refreshToken": zod.string().nullish()
})

export const AuthControllerAccountLinkResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerAccountUnlinkBody = zod.object({
  "providerId": zod.enum(['credential', 'google', 'kakao', 'naver', 'github']),
  "accountId": zod.string()
})

export const AuthControllerAccountUnlinkResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerUserUnregisterResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerGenerate2FAResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "secret": zod.string().describe('Base32 encoded secret key')
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerTurnOn2FABody = zod.object({
  "code": zod.string()
})

export const AuthControllerTurnOn2FAResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerTurnOff2FAResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const authControllerChangePasswordBodyNewPasswordMin = 10;
export const authControllerChangePasswordBodyNewPasswordMax = 24;



export const AuthControllerChangePasswordBody = zod.object({
  "currentPassword": zod.string(),
  "newPassword": zod.string().min(authControllerChangePasswordBodyNewPasswordMin).max(authControllerChangePasswordBodyNewPasswordMax),
  "confirmPassword": zod.string()
})

export const AuthControllerChangePasswordResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerDeferPasswordChangeResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerIssuePhoneChangeChallengeBody = zod.object({
  "phoneNumber": zod.string().describe('New Korean mobile phone number')
})

export const AuthControllerIssuePhoneChangeChallengeResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean(),
  "challengeId": zod.uuid(),
  "expiresIn": zod.number().describe('Challenge validity in seconds'),
  "mockCode": zod.string().describe('Temporary mock verification code')
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerVerifyIdentityPhoneChangeBody = zod.object({
  "identityVerificationId": zod.string().describe('PortOne Identity Verification ID')
})

export const AuthControllerVerifyIdentityPhoneChangeResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean(),
  "name": zod.string(),
  "phoneNumber": zod.string(),
  "phoneNumberVerified": zod.boolean(),
  "birthDate": zod.string().nullish(),
  "gender": zod.enum(['MALE', 'FEMALE']).nullish()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerIssueEmailChangeChallengeBody = zod.object({
  "newEmail": zod.string().describe('New email address to change to'),
  "currentPassword": zod.string().optional().describe('Current password for verification')
})

export const AuthControllerIssueEmailChangeChallengeResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean(),
  "challengeId": zod.uuid(),
  "expiresIn": zod.number().describe('Expiration in seconds'),
  "newEmail": zod.string(),
  "devMagicLink": zod.string().nullish().describe('Direct verification link for development environment')
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

export const AuthControllerVerifyEmailChangeBody = zod.object({
  "challengeId": zod.uuid(),
  "token": zod.string().describe('Magic link verification token')
})

export const AuthControllerVerifyEmailChangeResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean(),
  "email": zod.string(),
  "emailVerified": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

