/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateSupportMessageRequestDto,
  SupportControllerCreateMessageV1200,
  SupportControllerGetRoomV1200,
  SupportControllerListMessagesV1200,
  SupportControllerListRoomsV1200,
  SupportControllerListRoomsV1Params,
  SupportControllerUpdateRoomV1200,
  UpdateSupportRoomRequestDto
} from '../../model';

import { axios } from '../../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const supportControllerListRoomsV1 = (
    params?: SupportControllerListRoomsV1Params,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<SupportControllerListRoomsV1200>(
      {url: `/api/v1/support/rooms`, method: 'GET',
        params, signal
    },
      options);
    }




export const getSupportControllerListRoomsV1QueryKey = (params?: SupportControllerListRoomsV1Params,) => {
    return [
    `/api/v1/support/rooms`, ...(params ? [params] : [])
    ] as const;
    }


export const getSupportControllerListRoomsV1QueryOptions = <TData = Awaited<ReturnType<typeof supportControllerListRoomsV1>>, TError = unknown>(params?: SupportControllerListRoomsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof supportControllerListRoomsV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSupportControllerListRoomsV1QueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof supportControllerListRoomsV1>>> = ({ signal }) => supportControllerListRoomsV1(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof supportControllerListRoomsV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SupportControllerListRoomsV1QueryResult = NonNullable<Awaited<ReturnType<typeof supportControllerListRoomsV1>>>
export type SupportControllerListRoomsV1QueryError = unknown


export function useSupportControllerListRoomsV1<TData = Awaited<ReturnType<typeof supportControllerListRoomsV1>>, TError = unknown>(
 params: undefined |  SupportControllerListRoomsV1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof supportControllerListRoomsV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof supportControllerListRoomsV1>>,
          TError,
          Awaited<ReturnType<typeof supportControllerListRoomsV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSupportControllerListRoomsV1<TData = Awaited<ReturnType<typeof supportControllerListRoomsV1>>, TError = unknown>(
 params?: SupportControllerListRoomsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof supportControllerListRoomsV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof supportControllerListRoomsV1>>,
          TError,
          Awaited<ReturnType<typeof supportControllerListRoomsV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSupportControllerListRoomsV1<TData = Awaited<ReturnType<typeof supportControllerListRoomsV1>>, TError = unknown>(
 params?: SupportControllerListRoomsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof supportControllerListRoomsV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSupportControllerListRoomsV1<TData = Awaited<ReturnType<typeof supportControllerListRoomsV1>>, TError = unknown>(
 params?: SupportControllerListRoomsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof supportControllerListRoomsV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSupportControllerListRoomsV1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const supportControllerGetRoomV1 = (
    roomId: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<SupportControllerGetRoomV1200>(
      {url: `/api/v1/support/rooms/${roomId}`, method: 'GET', signal
    },
      options);
    }




export const getSupportControllerGetRoomV1QueryKey = (roomId: string,) => {
    return [
    `/api/v1/support/rooms/${roomId}`
    ] as const;
    }


export const getSupportControllerGetRoomV1QueryOptions = <TData = Awaited<ReturnType<typeof supportControllerGetRoomV1>>, TError = unknown>(roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof supportControllerGetRoomV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSupportControllerGetRoomV1QueryKey(roomId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof supportControllerGetRoomV1>>> = ({ signal }) => supportControllerGetRoomV1(roomId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: roomId !== null && roomId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof supportControllerGetRoomV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SupportControllerGetRoomV1QueryResult = NonNullable<Awaited<ReturnType<typeof supportControllerGetRoomV1>>>
export type SupportControllerGetRoomV1QueryError = unknown


export function useSupportControllerGetRoomV1<TData = Awaited<ReturnType<typeof supportControllerGetRoomV1>>, TError = unknown>(
 roomId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof supportControllerGetRoomV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof supportControllerGetRoomV1>>,
          TError,
          Awaited<ReturnType<typeof supportControllerGetRoomV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSupportControllerGetRoomV1<TData = Awaited<ReturnType<typeof supportControllerGetRoomV1>>, TError = unknown>(
 roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof supportControllerGetRoomV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof supportControllerGetRoomV1>>,
          TError,
          Awaited<ReturnType<typeof supportControllerGetRoomV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSupportControllerGetRoomV1<TData = Awaited<ReturnType<typeof supportControllerGetRoomV1>>, TError = unknown>(
 roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof supportControllerGetRoomV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSupportControllerGetRoomV1<TData = Awaited<ReturnType<typeof supportControllerGetRoomV1>>, TError = unknown>(
 roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof supportControllerGetRoomV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSupportControllerGetRoomV1QueryOptions(roomId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const supportControllerUpdateRoomV1 = (
    roomId: string,
    updateSupportRoomRequestDto: UpdateSupportRoomRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<SupportControllerUpdateRoomV1200>(
      {url: `/api/v1/support/rooms/${roomId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSupportRoomRequestDto, signal
    },
      options);
    }




export const getSupportControllerUpdateRoomV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof supportControllerUpdateRoomV1>>, TError,{roomId: string;data: UpdateSupportRoomRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof supportControllerUpdateRoomV1>>, TError,{roomId: string;data: UpdateSupportRoomRequestDto}, TContext> => {

const mutationKey = ['supportControllerUpdateRoomV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof supportControllerUpdateRoomV1>>, {roomId: string;data: UpdateSupportRoomRequestDto}> = (props) => {
          const {roomId,data} = props ?? {};

          return  supportControllerUpdateRoomV1(roomId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SupportControllerUpdateRoomV1MutationResult = NonNullable<Awaited<ReturnType<typeof supportControllerUpdateRoomV1>>>
    export type SupportControllerUpdateRoomV1MutationBody = UpdateSupportRoomRequestDto
    export type SupportControllerUpdateRoomV1MutationError = unknown

    export const useSupportControllerUpdateRoomV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof supportControllerUpdateRoomV1>>, TError,{roomId: string;data: UpdateSupportRoomRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof supportControllerUpdateRoomV1>>,
        TError,
        {roomId: string;data: UpdateSupportRoomRequestDto},
        TContext
      > => {
      return useMutation(getSupportControllerUpdateRoomV1MutationOptions(options), queryClient);
    }
    export const supportControllerListMessagesV1 = (
    roomId: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<SupportControllerListMessagesV1200>(
      {url: `/api/v1/support/rooms/${roomId}/messages`, method: 'GET', signal
    },
      options);
    }




export const getSupportControllerListMessagesV1QueryKey = (roomId: string,) => {
    return [
    `/api/v1/support/rooms/${roomId}/messages`
    ] as const;
    }


export const getSupportControllerListMessagesV1QueryOptions = <TData = Awaited<ReturnType<typeof supportControllerListMessagesV1>>, TError = unknown>(roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof supportControllerListMessagesV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSupportControllerListMessagesV1QueryKey(roomId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof supportControllerListMessagesV1>>> = ({ signal }) => supportControllerListMessagesV1(roomId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: roomId !== null && roomId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof supportControllerListMessagesV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SupportControllerListMessagesV1QueryResult = NonNullable<Awaited<ReturnType<typeof supportControllerListMessagesV1>>>
export type SupportControllerListMessagesV1QueryError = unknown


export function useSupportControllerListMessagesV1<TData = Awaited<ReturnType<typeof supportControllerListMessagesV1>>, TError = unknown>(
 roomId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof supportControllerListMessagesV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof supportControllerListMessagesV1>>,
          TError,
          Awaited<ReturnType<typeof supportControllerListMessagesV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSupportControllerListMessagesV1<TData = Awaited<ReturnType<typeof supportControllerListMessagesV1>>, TError = unknown>(
 roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof supportControllerListMessagesV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof supportControllerListMessagesV1>>,
          TError,
          Awaited<ReturnType<typeof supportControllerListMessagesV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSupportControllerListMessagesV1<TData = Awaited<ReturnType<typeof supportControllerListMessagesV1>>, TError = unknown>(
 roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof supportControllerListMessagesV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSupportControllerListMessagesV1<TData = Awaited<ReturnType<typeof supportControllerListMessagesV1>>, TError = unknown>(
 roomId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof supportControllerListMessagesV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSupportControllerListMessagesV1QueryOptions(roomId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const supportControllerCreateMessageV1 = (
    roomId: string,
    createSupportMessageRequestDto: CreateSupportMessageRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<SupportControllerCreateMessageV1200>(
      {url: `/api/v1/support/rooms/${roomId}/messages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSupportMessageRequestDto, signal
    },
      options);
    }




export const getSupportControllerCreateMessageV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof supportControllerCreateMessageV1>>, TError,{roomId: string;data: CreateSupportMessageRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof supportControllerCreateMessageV1>>, TError,{roomId: string;data: CreateSupportMessageRequestDto}, TContext> => {

const mutationKey = ['supportControllerCreateMessageV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof supportControllerCreateMessageV1>>, {roomId: string;data: CreateSupportMessageRequestDto}> = (props) => {
          const {roomId,data} = props ?? {};

          return  supportControllerCreateMessageV1(roomId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SupportControllerCreateMessageV1MutationResult = NonNullable<Awaited<ReturnType<typeof supportControllerCreateMessageV1>>>
    export type SupportControllerCreateMessageV1MutationBody = CreateSupportMessageRequestDto
    export type SupportControllerCreateMessageV1MutationError = unknown

    export const useSupportControllerCreateMessageV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof supportControllerCreateMessageV1>>, TError,{roomId: string;data: CreateSupportMessageRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof supportControllerCreateMessageV1>>,
        TError,
        {roomId: string;data: CreateSupportMessageRequestDto},
        TContext
      > => {
      return useMutation(getSupportControllerCreateMessageV1MutationOptions(options), queryClient);
    }
