/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import type { AuthControllerRequestEmailVerificationV1200Meta } from './authControllerRequestEmailVerificationV1200Meta';
import type { RequestEmailVerificationResponseDto } from './requestEmailVerificationResponseDto';

export type AuthControllerRequestEmailVerificationV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: RequestEmailVerificationResponseDto;
  message?: string;
  meta?: AuthControllerRequestEmailVerificationV1200Meta;
};
