/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import type { AuthControllerGetPolicyV1200Meta } from './authControllerGetPolicyV1200Meta';
import type { AuthPolicyResponseDto } from './authPolicyResponseDto';

export type AuthControllerGetPolicyV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: AuthPolicyResponseDto;
  message?: string;
  meta?: AuthControllerGetPolicyV1200Meta;
};
