/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerDetailResponse } from './customerDetailResponse';
import type { CustomersControllerGetMeV1200Meta } from './customersControllerGetMeV1200Meta';

export type CustomersControllerGetMeV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: CustomerDetailResponse;
  message?: string;
  meta?: CustomersControllerGetMeV1200Meta;
};
