/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import type { FaqListResponse } from './faqListResponse';
import type { FaqsControllerGetFaqsV1200Meta } from './faqsControllerGetFaqsV1200Meta';

export type FaqsControllerGetFaqsV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: FaqListResponse;
  message?: string;
  meta?: FaqsControllerGetFaqsV1200Meta;
};
