/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */

export type FaqsControllerGetFaqsV1SortItem = typeof FaqsControllerGetFaqsV1SortItem[keyof typeof FaqsControllerGetFaqsV1SortItem];


export const FaqsControllerGetFaqsV1SortItem = {
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
} as const;
