/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */

export type HealthControllerCheckLiveV1503Status = typeof HealthControllerCheckLiveV1503Status[keyof typeof HealthControllerCheckLiveV1503Status];


export const HealthControllerCheckLiveV1503Status = {
  error: 'error',
  shutting_down: 'shutting_down',
} as const;
