/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */

export type HealthControllerCheck200Status = typeof HealthControllerCheck200Status[keyof typeof HealthControllerCheck200Status];


export const HealthControllerCheck200Status = {
  ok: 'ok',
  degraded: 'degraded',
} as const;
