/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */

export type HealthControllerCheckReadyV1200Status = typeof HealthControllerCheckReadyV1200Status[keyof typeof HealthControllerCheckReadyV1200Status];


export const HealthControllerCheckReadyV1200Status = {
  ok: 'ok',
  degraded: 'degraded',
} as const;
