/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import type { AdminServiceTermGroupItem } from './adminServiceTermGroupItem';
import type { InternalServiceTermsControllerUpdateGroupV1200Meta } from './internalServiceTermsControllerUpdateGroupV1200Meta';

export type InternalServiceTermsControllerUpdateGroupV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: AdminServiceTermGroupItem;
  message?: string;
  meta?: InternalServiceTermsControllerUpdateGroupV1200Meta;
};
