/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import type { InternalServiceTermsControllerDeleteV1200Meta } from './internalServiceTermsControllerDeleteV1200Meta';
import type { Object } from './object';

export type InternalServiceTermsControllerDeleteV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: Object;
  message?: string;
  meta?: InternalServiceTermsControllerDeleteV1200Meta;
};
