/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import type { AdminServiceTermItem } from './adminServiceTermItem';
import type { InternalServiceTermsControllerCreateV1201Meta } from './internalServiceTermsControllerCreateV1201Meta';

export type InternalServiceTermsControllerCreateV1201 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: AdminServiceTermItem;
  message?: string;
  meta?: InternalServiceTermsControllerCreateV1201Meta;
};
