/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */

export interface MeResponse {
  /** 사용자 고유 식별자 */
  id: string;
  /** 사용자 이메일 */
  email: string;
  /** 사용자 이름 */
  name: string;
  /**
     * 프로필 아바타 이미지
     * @nullable
     */
  image?: string | null;
  /**
     * 연락처
     * @nullable
     */
  phoneNumber?: string | null;
  /** 2단계 인증(2FA) 활성화 여부 */
  twoFactorEnabled: boolean;
  /** 본인인증 완료 여부 */
  phoneNumberVerified: boolean;
  /** 현재 app.config.ts 비밀번호 정책에 따른 만료 여부 */
  passwordExpired: boolean;
  /** 역할 코드 */
  roleCode: string;
  /** 보유 권한 목록 */
  permissions: string[];
  /**
     * 최근 로그인 일시
     * @nullable
     */
  lastLoginAt?: string | null;
}
