/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import type { QnaControllerGetV1200Meta } from './qnaControllerGetV1200Meta';
import type { QnaItem } from './qnaItem';

export type QnaControllerGetV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: QnaItem;
  message?: string;
  meta?: QnaControllerGetV1200Meta;
};
