/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import type { QnaInternalControllerListV1Category } from './qnaInternalControllerListV1Category';
import type { QnaInternalControllerListV1Priority } from './qnaInternalControllerListV1Priority';
import type { QnaInternalControllerListV1Status } from './qnaInternalControllerListV1Status';
import type { SortDirection } from './sortDirection';

export type QnaInternalControllerListV1Params = {
sort?: string[];
direction?: SortDirection[];
search?: string;
page?: number;
/**
 * @maximum 100
 */
limit?: number;
category?: QnaInternalControllerListV1Category;
status?: QnaInternalControllerListV1Status;
priority?: QnaInternalControllerListV1Priority;
};
