/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterRequestDto {
  email: string;
  /**
     * @minLength 8
     * @maxLength 256
     */
  password: string;
  /** @maxLength 120 */
  name: string;
}
