/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */

export interface ResetPasswordDto {
  challengeId: string;
  token: string;
  /**
     * @minLength 8
     * @maxLength 256
     */
  newPassword: string;
}
