/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceTermDetailResponse } from './serviceTermDetailResponse';
import type { ServiceTermsControllerGetTermV1200Meta } from './serviceTermsControllerGetTermV1200Meta';

export type ServiceTermsControllerGetTermV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: ServiceTermDetailResponse;
  message?: string;
  meta?: ServiceTermsControllerGetTermV1200Meta;
};
