/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */

export interface ServiceTermItem {
  id: string;
  groupId: string;
  title: string;
  version: string;
  content: string;
  isRequired: boolean;
  sortOrder: number;
  publishedAt: string;
  createdAt: string;
  updatedAt: string;
}
