/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceTermListResponse } from './serviceTermListResponse';
import type { ServiceTermsControllerGetTermsV1200Meta } from './serviceTermsControllerGetTermsV1200Meta';

export type ServiceTermsControllerGetTermsV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: ServiceTermListResponse;
  message?: string;
  meta?: ServiceTermsControllerGetTermsV1200Meta;
};
