/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import type { SupportControllerListRoomsV1Status } from './supportControllerListRoomsV1Status';

export type SupportControllerListRoomsV1Params = {
search?: string;
page?: unknown;
limit?: unknown;
status?: SupportControllerListRoomsV1Status;
};
