/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import type { SupportControllerListRoomsV1200Meta } from './supportControllerListRoomsV1200Meta';
import type { SupportRoomPageResponseDto } from './supportRoomPageResponseDto';

export type SupportControllerListRoomsV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: SupportRoomPageResponseDto;
  message?: string;
  meta?: SupportControllerListRoomsV1200Meta;
};
