/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import type { OperationNoticeResponseDto } from './operationNoticeResponseDto';
import type { SystemConfigsControllerGetOperationNoticeV1200Meta } from './systemConfigsControllerGetOperationNoticeV1200Meta';

export type SystemConfigsControllerGetOperationNoticeV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: OperationNoticeResponseDto;
  message?: string;
  meta?: SystemConfigsControllerGetOperationNoticeV1200Meta;
};
