/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import type { MaintenanceStatusResponseDto } from './maintenanceStatusResponseDto';
import type { SystemConfigsControllerGetMaintenanceStatusV1200Meta } from './systemConfigsControllerGetMaintenanceStatusV1200Meta';

export type SystemConfigsControllerGetMaintenanceStatusV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: MaintenanceStatusResponseDto;
  message?: string;
  meta?: SystemConfigsControllerGetMaintenanceStatusV1200Meta;
};
