/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Service API
 * Data Plane Service API Service
 * OpenAPI spec version: 1.0.0
 */
import type { PublicSystemConfigListResponseDto } from './publicSystemConfigListResponseDto';
import type { SystemConfigsControllerListConfigsV1200Meta } from './systemConfigsControllerListConfigsV1200Meta';

export type SystemConfigsControllerListConfigsV1200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: PublicSystemConfigListResponseDto;
  message?: string;
  meta?: SystemConfigsControllerListConfigsV1200Meta;
};
