/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type {
  TermsControllerGetAgreements200,
  TermsControllerGetTerms200,
  TermsControllerUpdateAgreements200,
  UpdateAgreementsRequestDto
} from '../../model';

import { axios } from '../../../../core/config/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const termsControllerGetTerms = (

 options?: SecondParameter<typeof axios<TermsControllerGetTerms200>>,) => {
      return axios<TermsControllerGetTerms200>(
      {url: `/api/v1/terms`, method: 'GET'
    },
      options);
    }
  export const termsControllerGetAgreements = (

 options?: SecondParameter<typeof axios<TermsControllerGetAgreements200>>,) => {
      return axios<TermsControllerGetAgreements200>(
      {url: `/api/v1/terms/agreements`, method: 'GET'
    },
      options);
    }
  export const termsControllerUpdateAgreements = (
    updateAgreementsRequestDto: UpdateAgreementsRequestDto,
 options?: SecondParameter<typeof axios<TermsControllerUpdateAgreements200>>,) => {
      return axios<TermsControllerUpdateAgreements200>(
      {url: `/api/v1/terms/agree`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateAgreementsRequestDto
    },
      options);
    }
  export type TermsControllerGetTermsResult = NonNullable<Awaited<ReturnType<typeof termsControllerGetTerms>>>
export type TermsControllerGetAgreementsResult = NonNullable<Awaited<ReturnType<typeof termsControllerGetAgreements>>>
export type TermsControllerUpdateAgreementsResult = NonNullable<Awaited<ReturnType<typeof termsControllerUpdateAgreements>>>
