/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PermissionsControllerGetPermissionsV1200
} from '../../model';

import { axios } from '../../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const permissionsControllerGetPermissionsV1 = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<PermissionsControllerGetPermissionsV1200>(
      {url: `/api/v1/permissions`, method: 'GET', signal
    },
      options);
    }




export const getPermissionsControllerGetPermissionsV1QueryKey = () => {
    return [
    `/api/v1/permissions`
    ] as const;
    }


export const getPermissionsControllerGetPermissionsV1QueryOptions = <TData = Awaited<ReturnType<typeof permissionsControllerGetPermissionsV1>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof permissionsControllerGetPermissionsV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPermissionsControllerGetPermissionsV1QueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof permissionsControllerGetPermissionsV1>>> = ({ signal }) => permissionsControllerGetPermissionsV1(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof permissionsControllerGetPermissionsV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PermissionsControllerGetPermissionsV1QueryResult = NonNullable<Awaited<ReturnType<typeof permissionsControllerGetPermissionsV1>>>
export type PermissionsControllerGetPermissionsV1QueryError = unknown


export function usePermissionsControllerGetPermissionsV1<TData = Awaited<ReturnType<typeof permissionsControllerGetPermissionsV1>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof permissionsControllerGetPermissionsV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof permissionsControllerGetPermissionsV1>>,
          TError,
          Awaited<ReturnType<typeof permissionsControllerGetPermissionsV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePermissionsControllerGetPermissionsV1<TData = Awaited<ReturnType<typeof permissionsControllerGetPermissionsV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof permissionsControllerGetPermissionsV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof permissionsControllerGetPermissionsV1>>,
          TError,
          Awaited<ReturnType<typeof permissionsControllerGetPermissionsV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePermissionsControllerGetPermissionsV1<TData = Awaited<ReturnType<typeof permissionsControllerGetPermissionsV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof permissionsControllerGetPermissionsV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePermissionsControllerGetPermissionsV1<TData = Awaited<ReturnType<typeof permissionsControllerGetPermissionsV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof permissionsControllerGetPermissionsV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPermissionsControllerGetPermissionsV1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
