/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * 채널, 언어, 검색어로 필터링된 메시지 템플릿 목록을 조회합니다.
 * @summary 메시지 템플릿 목록 조회
 */
export const messageTemplatesControllerGetMessageTemplatesQueryPageDefault = 1;
export const messageTemplatesControllerGetMessageTemplatesQueryLimitDefault = 20;
export const messageTemplatesControllerGetMessageTemplatesQueryLimitMax = 100;



export const MessageTemplatesControllerGetMessageTemplatesQueryParams = zod.object({
  "sort": zod.array(zod.string()).optional(),
  "direction": zod.array(zod.enum(['asc', 'desc'])).optional(),
  "search": zod.string().optional().describe('코드\/이름\/제목 검색'),
  "page": zod.number().default(messageTemplatesControllerGetMessageTemplatesQueryPageDefault),
  "limit": zod.number().max(messageTemplatesControllerGetMessageTemplatesQueryLimitMax).default(messageTemplatesControllerGetMessageTemplatesQueryLimitDefault),
  "channel": zod.enum(['EMAIL', 'SLACK', 'IN_APP', 'SMS', 'ALIMTALK']).optional(),
  "locale": zod.string().optional()
})

export const MessageTemplatesControllerGetMessageTemplatesResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "page": zod.number(),
  "totalPages": zod.number(),
  "hasNextPage": zod.boolean(),
  "hasPrevPage": zod.boolean(),
  "totalCount": zod.number(),
  "items": zod.array(zod.object({
  "id": zod.string(),
  "code": zod.string(),
  "locale": zod.string(),
  "channel": zod.enum(['EMAIL', 'SLACK', 'IN_APP', 'SMS', 'ALIMTALK']).optional(),
  "name": zod.string(),
  "title": zod.string().nullish(),
  "body": zod.string(),
  "variables": zod.array(zod.string()),
  "description": zod.string().nullish(),
  "isActive": zod.boolean(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}))
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * 새로운 메시지 템플릿을 등록합니다.
 * @summary 메시지 템플릿 생성
 */
export const messageTemplatesControllerCreateMessageTemplateBodyCodeMax = 100;

export const messageTemplatesControllerCreateMessageTemplateBodyLocaleDefault = `ko`;
export const messageTemplatesControllerCreateMessageTemplateBodyLocaleMax = 10;

export const messageTemplatesControllerCreateMessageTemplateBodyNameMax = 100;

export const messageTemplatesControllerCreateMessageTemplateBodyTitleMax = 255;

export const messageTemplatesControllerCreateMessageTemplateBodyVariablesDefault = [];
export const messageTemplatesControllerCreateMessageTemplateBodyIsActiveDefault = true;

export const MessageTemplatesControllerCreateMessageTemplateBody = zod.object({
  "code": zod.string().max(messageTemplatesControllerCreateMessageTemplateBodyCodeMax),
  "locale": zod.string().max(messageTemplatesControllerCreateMessageTemplateBodyLocaleMax).default(messageTemplatesControllerCreateMessageTemplateBodyLocaleDefault),
  "channel": zod.enum(['EMAIL', 'SLACK', 'IN_APP', 'SMS', 'ALIMTALK']),
  "name": zod.string().max(messageTemplatesControllerCreateMessageTemplateBodyNameMax),
  "title": zod.string().max(messageTemplatesControllerCreateMessageTemplateBodyTitleMax).nullish(),
  "body": zod.string().describe('템플릿 본문 (Markdown\/HTML\/텍스트)'),
  "variables": zod.array(zod.string()).default(messageTemplatesControllerCreateMessageTemplateBodyVariablesDefault),
  "description": zod.string().nullish(),
  "isActive": zod.boolean().default(messageTemplatesControllerCreateMessageTemplateBodyIsActiveDefault)
})

export const MessageTemplatesControllerCreateMessageTemplateResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "id": zod.string(),
  "code": zod.string(),
  "locale": zod.string(),
  "channel": zod.enum(['EMAIL', 'SLACK', 'IN_APP', 'SMS', 'ALIMTALK']).optional(),
  "name": zod.string(),
  "title": zod.string().nullish(),
  "body": zod.string(),
  "variables": zod.array(zod.string()),
  "description": zod.string().nullish(),
  "isActive": zod.boolean(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * ID로 단일 메시지 템플릿 상세 정보를 조회합니다.
 * @summary 메시지 템플릿 상세 조회
 */
export const MessageTemplatesControllerGetMessageTemplateByIdParams = zod.object({
  "id": zod.string().describe('템플릿 ID')
})

export const MessageTemplatesControllerGetMessageTemplateByIdResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "id": zod.string(),
  "code": zod.string(),
  "locale": zod.string(),
  "channel": zod.enum(['EMAIL', 'SLACK', 'IN_APP', 'SMS', 'ALIMTALK']).optional(),
  "name": zod.string(),
  "title": zod.string().nullish(),
  "body": zod.string(),
  "variables": zod.array(zod.string()),
  "description": zod.string().nullish(),
  "isActive": zod.boolean(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * 템플릿의 제목, 본문, 활성화 여부를 수정합니다.
 * @summary 메시지 템플릿 수정
 */
export const MessageTemplatesControllerUpdateMessageTemplateParams = zod.object({
  "id": zod.string().describe('템플릿 ID')
})

export const MessageTemplatesControllerUpdateMessageTemplateBody = zod.object({
  "title": zod.string().nullish(),
  "body": zod.string().optional(),
  "isActive": zod.boolean().optional()
})

export const MessageTemplatesControllerUpdateMessageTemplateResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "id": zod.string(),
  "code": zod.string(),
  "locale": zod.string(),
  "channel": zod.enum(['EMAIL', 'SLACK', 'IN_APP', 'SMS', 'ALIMTALK']).optional(),
  "name": zod.string(),
  "title": zod.string().nullish(),
  "body": zod.string(),
  "variables": zod.array(zod.string()),
  "description": zod.string().nullish(),
  "isActive": zod.boolean(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * 템플릿을 삭제(Soft Delete)합니다.
 * @summary 메시지 템플릿 삭제
 */
export const MessageTemplatesControllerDeleteMessageTemplateParams = zod.object({
  "id": zod.string().describe('템플릿 ID')
})

export const MessageTemplatesControllerDeleteMessageTemplateResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "ok": zod.boolean()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * 샘플 변수를 치환하여 렌더링된 제목과 본문 미리보기를 반환합니다.
 * @summary 메시지 템플릿 미리보기 렌더링
 */
export const MessageTemplatesControllerRenderPreviewParams = zod.object({
  "id": zod.string().describe('템플릿 ID')
})

export const MessageTemplatesControllerRenderPreviewBody = zod.object({
  "variables": zod.record(zod.string(), zod.unknown()).optional().describe('치환 테스트용 샘플 변수 객체')
})

export const MessageTemplatesControllerRenderPreviewResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "title": zod.string().nullish(),
  "body": zod.string(),
  "channel": zod.string(),
  "locale": zod.string()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

/**
 * 관리자 이메일, 슬랙 또는 인앱 알림으로 실제 테스트 발송을 수행합니다.
 * @summary 메시지 템플릿 테스트 발송
 */
export const MessageTemplatesControllerTestSendParams = zod.object({
  "id": zod.string().describe('템플릿 ID')
})

export const MessageTemplatesControllerTestSendBody = zod.object({
  "recipientEmail": zod.string().optional().describe('테스트 수신 이메일 주소'),
  "variables": zod.record(zod.string(), zod.unknown()).optional().describe('치환용 샘플 변수')
})

export const MessageTemplatesControllerTestSendResponse = zod.object({
  "success": zod.boolean(),
  "statusCode": zod.number(),
  "path": zod.string(),
  "requestId": zod.string(),
  "timestamp": zod.string(),
  "data": zod.object({
  "success": zod.boolean(),
  "message": zod.string()
}),
  "message": zod.string().optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})

