/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BanUserRequestDto,
  CreateUserRequestDto,
  UpdateUserRoleRequestDto,
  UsersControllerBanUserV1200,
  UsersControllerCreateUserV1201,
  UsersControllerDeleteUserV1200,
  UsersControllerGetUserByIdV1200,
  UsersControllerGetUserOverviewV1200,
  UsersControllerGetUsersV1200,
  UsersControllerGetUsersV1Params,
  UsersControllerResetUserTwoFactorV1200,
  UsersControllerRestoreUserV1200,
  UsersControllerUnbanUserV1200,
  UsersControllerUpdateUserRoleV1200
} from '../../model';

import { axios } from '../../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const usersControllerGetUsersV1 = (
    params?: UsersControllerGetUsersV1Params,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<UsersControllerGetUsersV1200>(
      {url: `/api/v1/users`, method: 'GET',
        params, signal
    },
      options);
    }




export const getUsersControllerGetUsersV1QueryKey = (params?: UsersControllerGetUsersV1Params,) => {
    return [
    `/api/v1/users`, ...(params ? [params] : [])
    ] as const;
    }


export const getUsersControllerGetUsersV1QueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetUsersV1>>, TError = unknown>(params?: UsersControllerGetUsersV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUsersV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetUsersV1QueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetUsersV1>>> = ({ signal }) => usersControllerGetUsersV1(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUsersV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerGetUsersV1QueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetUsersV1>>>
export type UsersControllerGetUsersV1QueryError = unknown


export function useUsersControllerGetUsersV1<TData = Awaited<ReturnType<typeof usersControllerGetUsersV1>>, TError = unknown>(
 params: undefined |  UsersControllerGetUsersV1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUsersV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUsersV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUsersV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetUsersV1<TData = Awaited<ReturnType<typeof usersControllerGetUsersV1>>, TError = unknown>(
 params?: UsersControllerGetUsersV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUsersV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUsersV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUsersV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetUsersV1<TData = Awaited<ReturnType<typeof usersControllerGetUsersV1>>, TError = unknown>(
 params?: UsersControllerGetUsersV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUsersV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersControllerGetUsersV1<TData = Awaited<ReturnType<typeof usersControllerGetUsersV1>>, TError = unknown>(
 params?: UsersControllerGetUsersV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUsersV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerGetUsersV1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const usersControllerCreateUserV1 = (
    createUserRequestDto: CreateUserRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<UsersControllerCreateUserV1201>(
      {url: `/api/v1/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserRequestDto, signal
    },
      options);
    }




export const getUsersControllerCreateUserV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerCreateUserV1>>, TError,{data: CreateUserRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerCreateUserV1>>, TError,{data: CreateUserRequestDto}, TContext> => {

const mutationKey = ['usersControllerCreateUserV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerCreateUserV1>>, {data: CreateUserRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  usersControllerCreateUserV1(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerCreateUserV1MutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerCreateUserV1>>>
    export type UsersControllerCreateUserV1MutationBody = CreateUserRequestDto
    export type UsersControllerCreateUserV1MutationError = unknown

    export const useUsersControllerCreateUserV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerCreateUserV1>>, TError,{data: CreateUserRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerCreateUserV1>>,
        TError,
        {data: CreateUserRequestDto},
        TContext
      > => {
      return useMutation(getUsersControllerCreateUserV1MutationOptions(options), queryClient);
    }
    export const usersControllerGetUserOverviewV1 = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<UsersControllerGetUserOverviewV1200>(
      {url: `/api/v1/users/overview`, method: 'GET', signal
    },
      options);
    }




export const getUsersControllerGetUserOverviewV1QueryKey = () => {
    return [
    `/api/v1/users/overview`
    ] as const;
    }


export const getUsersControllerGetUserOverviewV1QueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetUserOverviewV1>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserOverviewV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetUserOverviewV1QueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetUserOverviewV1>>> = ({ signal }) => usersControllerGetUserOverviewV1(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserOverviewV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerGetUserOverviewV1QueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetUserOverviewV1>>>
export type UsersControllerGetUserOverviewV1QueryError = unknown


export function useUsersControllerGetUserOverviewV1<TData = Awaited<ReturnType<typeof usersControllerGetUserOverviewV1>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserOverviewV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUserOverviewV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUserOverviewV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetUserOverviewV1<TData = Awaited<ReturnType<typeof usersControllerGetUserOverviewV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserOverviewV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUserOverviewV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUserOverviewV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetUserOverviewV1<TData = Awaited<ReturnType<typeof usersControllerGetUserOverviewV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserOverviewV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersControllerGetUserOverviewV1<TData = Awaited<ReturnType<typeof usersControllerGetUserOverviewV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserOverviewV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerGetUserOverviewV1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const usersControllerGetUserByIdV1 = (
    id: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<UsersControllerGetUserByIdV1200>(
      {url: `/api/v1/users/${id}`, method: 'GET', signal
    },
      options);
    }




export const getUsersControllerGetUserByIdV1QueryKey = (id: string,) => {
    return [
    `/api/v1/users/${id}`
    ] as const;
    }


export const getUsersControllerGetUserByIdV1QueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetUserByIdV1>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserByIdV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetUserByIdV1QueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetUserByIdV1>>> = ({ signal }) => usersControllerGetUserByIdV1(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserByIdV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerGetUserByIdV1QueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetUserByIdV1>>>
export type UsersControllerGetUserByIdV1QueryError = unknown


export function useUsersControllerGetUserByIdV1<TData = Awaited<ReturnType<typeof usersControllerGetUserByIdV1>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserByIdV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUserByIdV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUserByIdV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetUserByIdV1<TData = Awaited<ReturnType<typeof usersControllerGetUserByIdV1>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserByIdV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUserByIdV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUserByIdV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetUserByIdV1<TData = Awaited<ReturnType<typeof usersControllerGetUserByIdV1>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserByIdV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersControllerGetUserByIdV1<TData = Awaited<ReturnType<typeof usersControllerGetUserByIdV1>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserByIdV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerGetUserByIdV1QueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const usersControllerDeleteUserV1 = (
    id: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<UsersControllerDeleteUserV1200>(
      {url: `/api/v1/users/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getUsersControllerDeleteUserV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerDeleteUserV1>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerDeleteUserV1>>, TError,{id: string}, TContext> => {

const mutationKey = ['usersControllerDeleteUserV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerDeleteUserV1>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  usersControllerDeleteUserV1(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerDeleteUserV1MutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerDeleteUserV1>>>

    export type UsersControllerDeleteUserV1MutationError = unknown

    export const useUsersControllerDeleteUserV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerDeleteUserV1>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerDeleteUserV1>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getUsersControllerDeleteUserV1MutationOptions(options), queryClient);
    }
    export const usersControllerBanUserV1 = (
    id: string,
    banUserRequestDto: BanUserRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<UsersControllerBanUserV1200>(
      {url: `/api/v1/users/${id}/ban`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: banUserRequestDto, signal
    },
      options);
    }




export const getUsersControllerBanUserV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerBanUserV1>>, TError,{id: string;data: BanUserRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerBanUserV1>>, TError,{id: string;data: BanUserRequestDto}, TContext> => {

const mutationKey = ['usersControllerBanUserV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerBanUserV1>>, {id: string;data: BanUserRequestDto}> = (props) => {
          const {id,data} = props ?? {};

          return  usersControllerBanUserV1(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerBanUserV1MutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerBanUserV1>>>
    export type UsersControllerBanUserV1MutationBody = BanUserRequestDto
    export type UsersControllerBanUserV1MutationError = unknown

    export const useUsersControllerBanUserV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerBanUserV1>>, TError,{id: string;data: BanUserRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerBanUserV1>>,
        TError,
        {id: string;data: BanUserRequestDto},
        TContext
      > => {
      return useMutation(getUsersControllerBanUserV1MutationOptions(options), queryClient);
    }
    export const usersControllerUnbanUserV1 = (
    id: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<UsersControllerUnbanUserV1200>(
      {url: `/api/v1/users/${id}/unban`, method: 'POST', signal
    },
      options);
    }




export const getUsersControllerUnbanUserV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerUnbanUserV1>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerUnbanUserV1>>, TError,{id: string}, TContext> => {

const mutationKey = ['usersControllerUnbanUserV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerUnbanUserV1>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  usersControllerUnbanUserV1(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerUnbanUserV1MutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerUnbanUserV1>>>

    export type UsersControllerUnbanUserV1MutationError = unknown

    export const useUsersControllerUnbanUserV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerUnbanUserV1>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerUnbanUserV1>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getUsersControllerUnbanUserV1MutationOptions(options), queryClient);
    }
    export const usersControllerRestoreUserV1 = (
    id: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<UsersControllerRestoreUserV1200>(
      {url: `/api/v1/users/${id}/restore`, method: 'POST', signal
    },
      options);
    }




export const getUsersControllerRestoreUserV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerRestoreUserV1>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerRestoreUserV1>>, TError,{id: string}, TContext> => {

const mutationKey = ['usersControllerRestoreUserV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerRestoreUserV1>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  usersControllerRestoreUserV1(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerRestoreUserV1MutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerRestoreUserV1>>>

    export type UsersControllerRestoreUserV1MutationError = unknown

    export const useUsersControllerRestoreUserV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerRestoreUserV1>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerRestoreUserV1>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getUsersControllerRestoreUserV1MutationOptions(options), queryClient);
    }
    export const usersControllerUpdateUserRoleV1 = (
    id: string,
    updateUserRoleRequestDto: UpdateUserRoleRequestDto,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<UsersControllerUpdateUserRoleV1200>(
      {url: `/api/v1/users/${id}/role`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateUserRoleRequestDto, signal
    },
      options);
    }




export const getUsersControllerUpdateUserRoleV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerUpdateUserRoleV1>>, TError,{id: string;data: UpdateUserRoleRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerUpdateUserRoleV1>>, TError,{id: string;data: UpdateUserRoleRequestDto}, TContext> => {

const mutationKey = ['usersControllerUpdateUserRoleV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerUpdateUserRoleV1>>, {id: string;data: UpdateUserRoleRequestDto}> = (props) => {
          const {id,data} = props ?? {};

          return  usersControllerUpdateUserRoleV1(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerUpdateUserRoleV1MutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerUpdateUserRoleV1>>>
    export type UsersControllerUpdateUserRoleV1MutationBody = UpdateUserRoleRequestDto
    export type UsersControllerUpdateUserRoleV1MutationError = unknown

    export const useUsersControllerUpdateUserRoleV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerUpdateUserRoleV1>>, TError,{id: string;data: UpdateUserRoleRequestDto}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerUpdateUserRoleV1>>,
        TError,
        {id: string;data: UpdateUserRoleRequestDto},
        TContext
      > => {
      return useMutation(getUsersControllerUpdateUserRoleV1MutationOptions(options), queryClient);
    }
    export const usersControllerResetUserTwoFactorV1 = (
    id: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<UsersControllerResetUserTwoFactorV1200>(
      {url: `/api/v1/users/${id}/2fa/reset`, method: 'POST', signal
    },
      options);
    }




export const getUsersControllerResetUserTwoFactorV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerResetUserTwoFactorV1>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerResetUserTwoFactorV1>>, TError,{id: string}, TContext> => {

const mutationKey = ['usersControllerResetUserTwoFactorV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerResetUserTwoFactorV1>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  usersControllerResetUserTwoFactorV1(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerResetUserTwoFactorV1MutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerResetUserTwoFactorV1>>>

    export type UsersControllerResetUserTwoFactorV1MutationError = unknown

    export const useUsersControllerResetUserTwoFactorV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerResetUserTwoFactorV1>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerResetUserTwoFactorV1>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getUsersControllerResetUserTwoFactorV1MutationOptions(options), queryClient);
    }
