/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CustomersControllerGetCustomerV1200,
  CustomersControllerListCustomersV1200,
  CustomersControllerListCustomersV1Params
} from '../../model';

import { axios } from '../../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 고객 목록 조회
 */
export const customersControllerListCustomersV1 = (
    params?: CustomersControllerListCustomersV1Params,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<CustomersControllerListCustomersV1200>(
      {url: `/api/v1/customers`, method: 'GET',
        params, signal
    },
      options);
    }




export const getCustomersControllerListCustomersV1QueryKey = (params?: CustomersControllerListCustomersV1Params,) => {
    return [
    `/api/v1/customers`, ...(params ? [params] : [])
    ] as const;
    }


export const getCustomersControllerListCustomersV1QueryOptions = <TData = Awaited<ReturnType<typeof customersControllerListCustomersV1>>, TError = unknown>(params?: CustomersControllerListCustomersV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerListCustomersV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCustomersControllerListCustomersV1QueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof customersControllerListCustomersV1>>> = ({ signal }) => customersControllerListCustomersV1(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof customersControllerListCustomersV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CustomersControllerListCustomersV1QueryResult = NonNullable<Awaited<ReturnType<typeof customersControllerListCustomersV1>>>
export type CustomersControllerListCustomersV1QueryError = unknown


export function useCustomersControllerListCustomersV1<TData = Awaited<ReturnType<typeof customersControllerListCustomersV1>>, TError = unknown>(
 params: undefined |  CustomersControllerListCustomersV1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerListCustomersV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof customersControllerListCustomersV1>>,
          TError,
          Awaited<ReturnType<typeof customersControllerListCustomersV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCustomersControllerListCustomersV1<TData = Awaited<ReturnType<typeof customersControllerListCustomersV1>>, TError = unknown>(
 params?: CustomersControllerListCustomersV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerListCustomersV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof customersControllerListCustomersV1>>,
          TError,
          Awaited<ReturnType<typeof customersControllerListCustomersV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCustomersControllerListCustomersV1<TData = Awaited<ReturnType<typeof customersControllerListCustomersV1>>, TError = unknown>(
 params?: CustomersControllerListCustomersV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerListCustomersV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 고객 목록 조회
 */

export function useCustomersControllerListCustomersV1<TData = Awaited<ReturnType<typeof customersControllerListCustomersV1>>, TError = unknown>(
 params?: CustomersControllerListCustomersV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerListCustomersV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCustomersControllerListCustomersV1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary 고객 상세 조회
 */
export const customersControllerGetCustomerV1 = (
    id: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<CustomersControllerGetCustomerV1200>(
      {url: `/api/v1/customers/${id}`, method: 'GET', signal
    },
      options);
    }




export const getCustomersControllerGetCustomerV1QueryKey = (id: string,) => {
    return [
    `/api/v1/customers/${id}`
    ] as const;
    }


export const getCustomersControllerGetCustomerV1QueryOptions = <TData = Awaited<ReturnType<typeof customersControllerGetCustomerV1>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerGetCustomerV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCustomersControllerGetCustomerV1QueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof customersControllerGetCustomerV1>>> = ({ signal }) => customersControllerGetCustomerV1(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof customersControllerGetCustomerV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CustomersControllerGetCustomerV1QueryResult = NonNullable<Awaited<ReturnType<typeof customersControllerGetCustomerV1>>>
export type CustomersControllerGetCustomerV1QueryError = unknown


export function useCustomersControllerGetCustomerV1<TData = Awaited<ReturnType<typeof customersControllerGetCustomerV1>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerGetCustomerV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof customersControllerGetCustomerV1>>,
          TError,
          Awaited<ReturnType<typeof customersControllerGetCustomerV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCustomersControllerGetCustomerV1<TData = Awaited<ReturnType<typeof customersControllerGetCustomerV1>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerGetCustomerV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof customersControllerGetCustomerV1>>,
          TError,
          Awaited<ReturnType<typeof customersControllerGetCustomerV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCustomersControllerGetCustomerV1<TData = Awaited<ReturnType<typeof customersControllerGetCustomerV1>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerGetCustomerV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 고객 상세 조회
 */

export function useCustomersControllerGetCustomerV1<TData = Awaited<ReturnType<typeof customersControllerGetCustomerV1>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerGetCustomerV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCustomersControllerGetCustomerV1QueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






