/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Admin API
 * Control Plane Admin API Service
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HealthControllerCheckLiveV1200,
  HealthControllerCheckLiveV1503,
  HealthControllerCheckReadyV1200,
  HealthControllerCheckReadyV1503,
  HealthControllerCheckV1200,
  HealthControllerCheckV1503
} from '../../model';

import { axios } from '../../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Liveness Probe (프로세스 생존 여부 확인)
 */
export const healthControllerCheckLiveV1 = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<HealthControllerCheckLiveV1200>(
      {url: `/api/v1/health/live`, method: 'GET', signal
    },
      options);
    }




export const getHealthControllerCheckLiveV1QueryKey = () => {
    return [
    `/api/v1/health/live`
    ] as const;
    }


export const getHealthControllerCheckLiveV1QueryOptions = <TData = Awaited<ReturnType<typeof healthControllerCheckLiveV1>>, TError = HealthControllerCheckLiveV1503>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckLiveV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthControllerCheckLiveV1QueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthControllerCheckLiveV1>>> = ({ signal }) => healthControllerCheckLiveV1(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckLiveV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthControllerCheckLiveV1QueryResult = NonNullable<Awaited<ReturnType<typeof healthControllerCheckLiveV1>>>
export type HealthControllerCheckLiveV1QueryError = HealthControllerCheckLiveV1503


export function useHealthControllerCheckLiveV1<TData = Awaited<ReturnType<typeof healthControllerCheckLiveV1>>, TError = HealthControllerCheckLiveV1503>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckLiveV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerCheckLiveV1>>,
          TError,
          Awaited<ReturnType<typeof healthControllerCheckLiveV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthControllerCheckLiveV1<TData = Awaited<ReturnType<typeof healthControllerCheckLiveV1>>, TError = HealthControllerCheckLiveV1503>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckLiveV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerCheckLiveV1>>,
          TError,
          Awaited<ReturnType<typeof healthControllerCheckLiveV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthControllerCheckLiveV1<TData = Awaited<ReturnType<typeof healthControllerCheckLiveV1>>, TError = HealthControllerCheckLiveV1503>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckLiveV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Liveness Probe (프로세스 생존 여부 확인)
 */

export function useHealthControllerCheckLiveV1<TData = Awaited<ReturnType<typeof healthControllerCheckLiveV1>>, TError = HealthControllerCheckLiveV1503>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckLiveV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthControllerCheckLiveV1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Readiness Probe (DB 및 Redis 연결 상태 종합 점검)
 */
export const healthControllerCheckReadyV1 = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<HealthControllerCheckReadyV1200>(
      {url: `/api/v1/health/ready`, method: 'GET', signal
    },
      options);
    }




export const getHealthControllerCheckReadyV1QueryKey = () => {
    return [
    `/api/v1/health/ready`
    ] as const;
    }


export const getHealthControllerCheckReadyV1QueryOptions = <TData = Awaited<ReturnType<typeof healthControllerCheckReadyV1>>, TError = HealthControllerCheckReadyV1503>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckReadyV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthControllerCheckReadyV1QueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthControllerCheckReadyV1>>> = ({ signal }) => healthControllerCheckReadyV1(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckReadyV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthControllerCheckReadyV1QueryResult = NonNullable<Awaited<ReturnType<typeof healthControllerCheckReadyV1>>>
export type HealthControllerCheckReadyV1QueryError = HealthControllerCheckReadyV1503


export function useHealthControllerCheckReadyV1<TData = Awaited<ReturnType<typeof healthControllerCheckReadyV1>>, TError = HealthControllerCheckReadyV1503>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckReadyV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerCheckReadyV1>>,
          TError,
          Awaited<ReturnType<typeof healthControllerCheckReadyV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthControllerCheckReadyV1<TData = Awaited<ReturnType<typeof healthControllerCheckReadyV1>>, TError = HealthControllerCheckReadyV1503>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckReadyV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerCheckReadyV1>>,
          TError,
          Awaited<ReturnType<typeof healthControllerCheckReadyV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthControllerCheckReadyV1<TData = Awaited<ReturnType<typeof healthControllerCheckReadyV1>>, TError = HealthControllerCheckReadyV1503>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckReadyV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Readiness Probe (DB 및 Redis 연결 상태 종합 점검)
 */

export function useHealthControllerCheckReadyV1<TData = Awaited<ReturnType<typeof healthControllerCheckReadyV1>>, TError = HealthControllerCheckReadyV1503>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckReadyV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthControllerCheckReadyV1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary 기본 헬스체크 (하위 호환성 유지 - readiness 확인)
 */
export const healthControllerCheckV1 = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<HealthControllerCheckV1200>(
      {url: `/api/v1/health`, method: 'GET', signal
    },
      options);
    }




export const getHealthControllerCheckV1QueryKey = () => {
    return [
    `/api/v1/health`
    ] as const;
    }


export const getHealthControllerCheckV1QueryOptions = <TData = Awaited<ReturnType<typeof healthControllerCheckV1>>, TError = HealthControllerCheckV1503>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthControllerCheckV1QueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthControllerCheckV1>>> = ({ signal }) => healthControllerCheckV1(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthControllerCheckV1QueryResult = NonNullable<Awaited<ReturnType<typeof healthControllerCheckV1>>>
export type HealthControllerCheckV1QueryError = HealthControllerCheckV1503


export function useHealthControllerCheckV1<TData = Awaited<ReturnType<typeof healthControllerCheckV1>>, TError = HealthControllerCheckV1503>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerCheckV1>>,
          TError,
          Awaited<ReturnType<typeof healthControllerCheckV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthControllerCheckV1<TData = Awaited<ReturnType<typeof healthControllerCheckV1>>, TError = HealthControllerCheckV1503>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerCheckV1>>,
          TError,
          Awaited<ReturnType<typeof healthControllerCheckV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthControllerCheckV1<TData = Awaited<ReturnType<typeof healthControllerCheckV1>>, TError = HealthControllerCheckV1503>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 기본 헬스체크 (하위 호환성 유지 - readiness 확인)
 */

export function useHealthControllerCheckV1<TData = Awaited<ReturnType<typeof healthControllerCheckV1>>, TError = HealthControllerCheckV1503>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheckV1>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthControllerCheckV1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






