/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthProvider } from './authProvider';

export interface AccountUnlinkRequestDto {
  providerId: AuthProvider;
  accountId: string;
}
