/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */

export interface AccountUnlinkRequestDto {
  /** credential 또는 DB에 등록된 OAuth provider 식별자 */
  providerId: string;
  accountId: string;
}
