/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { ActivityErrorInfoDto } from './activityErrorInfoDto';
import type { ActivityLogItemDtoRequestBody } from './activityLogItemDtoRequestBody';
import type { ActivityLogItemDtoResponseBody } from './activityLogItemDtoResponseBody';

export interface ActivityLogItemDto {
  id: string;
  requestId: string;
  createdAt: string;
  method: string;
  url: string;
  statusCode: number;
  duration: number;
  /** @nullable */
  ip: string | null;
  /** @nullable */
  userAgent: string | null;
  level: string;
  /** @nullable */
  emailHash: string | null;
  /** @nullable */
  requestBody: ActivityLogItemDtoRequestBody;
  /** @nullable */
  responseBody: ActivityLogItemDtoResponseBody;
  /** @nullable */
  errorInfo: ActivityErrorInfoDto | null;
}
