/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 사용자 이메일 해시 (익명 식별자)
 * @nullable
 */
export type ActivityLogItemDtoEmailHash = { [key: string]: unknown } | null;
