/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 요청 바디 (JSON)
 * @nullable
 */
export type ActivityLogItemDtoRequestBody = { [key: string]: unknown } | null;
