/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { ActivityErrorInfoDtoDetails } from './activityErrorInfoDtoDetails';

export interface ActivityErrorInfoDto {
  /** 에러/예외 클래스명 (예: ApplicationError, TypeError) */
  name: string;
  /**
     * 비즈니스 에러 코드 (예: INVALID_TOKEN)
     * @nullable
     */
  code: string | null;
  /** 에러 메시지 */
  message: string;
  /**
     * 유효성 검사 등 상세 에러 내역
     * @nullable
     */
  details: ActivityErrorInfoDtoDetails;
  /**
     * 에러 호출 스택 트레이스
     * @nullable
     */
  stack: string | null;
  /**
     * DB 예외 시 실행 SQL 쿼리
     * @nullable
     */
  sql: string | null;
}
