/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminSystemConfigControllerUpdateSetting200Meta } from './adminSystemConfigControllerUpdateSetting200Meta';
import type { UpdateSystemConfigResponse } from './updateSystemConfigResponse';

export type AdminSystemConfigControllerUpdateSetting200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: UpdateSystemConfigResponse;
  message?: string;
  meta?: AdminSystemConfigControllerUpdateSetting200Meta;
};
