/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { GetHolidaysResponseDto } from './getHolidaysResponseDto';

export type AdminConfigControllerGetHolidays200 = {
  data: GetHolidaysResponseDto;
  meta: Record<string, unknown>;
  statusCode: number;
};
