/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { AgreementChannelsDto } from './agreementChannelsDto';

export interface AgreementMetadataDto {
  /** 채널별 수신 동의 */
  channels?: AgreementChannelsDto;
}
