/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */

export interface AgreementDto {
  id: string;
  version: string;
  content: string;
  /** @nullable */
  publishedAt: string | null;
  code: string;
  title: string;
  isRequired: boolean;
  sortOrder: number;
  isAgreed: boolean;
  /** @nullable */
  agreedTermId: string | null;
  /** @nullable */
  agreedVersion: string | null;
  /** @nullable */
  createdAt: string | null;
}
