/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { ApiValidationErrorDetailDtoConstraints } from './apiValidationErrorDetailDtoConstraints';

export interface ApiValidationErrorDetailDto {
  property: string;
  constraints?: ApiValidationErrorDetailDtoConstraints;
  children?: ApiValidationErrorDetailDto[];
}
