/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthControllerStopImpersonating200Meta } from './authControllerStopImpersonating200Meta';
import type { ImpersonationTokenResponseDto } from './impersonationTokenResponseDto';

export type AuthControllerStopImpersonating200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: ImpersonationTokenResponseDto;
  message?: string;
  meta?: AuthControllerStopImpersonating200Meta;
};
