/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthControllerIssuePasswordResetChallenge200Meta } from './authControllerIssuePasswordResetChallenge200Meta';
import type { IssuePasswordResetChallengeResponse } from './issuePasswordResetChallengeResponse';

export type AuthControllerIssuePasswordResetChallenge200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: IssuePasswordResetChallengeResponse;
  message?: string;
  meta?: AuthControllerIssuePasswordResetChallenge200Meta;
};
