/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthControllerUserUnregister200Meta } from './authControllerUserUnregister200Meta';
import type { UserUnregisterResponseDto } from './userUnregisterResponseDto';

export type AuthControllerUserUnregister200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: UserUnregisterResponseDto;
  message?: string;
  meta?: AuthControllerUserUnregister200Meta;
};
