/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthControllerFindId200Meta } from './authControllerFindId200Meta';
import type { FindIdResponse } from './findIdResponse';

export type AuthControllerFindId200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: FindIdResponse;
  message?: string;
  meta?: AuthControllerFindId200Meta;
};
