/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthControllerTurnOn2FA200Meta } from './authControllerTurnOn2FA200Meta';
import type { TwoFactorTurnOnResponseDto } from './twoFactorTurnOnResponseDto';

export type AuthControllerTurnOn2FA200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: TwoFactorTurnOnResponseDto;
  message?: string;
  meta?: AuthControllerTurnOn2FA200Meta;
};
