/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthControllerTurnOff2FA200Meta } from './authControllerTurnOff2FA200Meta';
import type { TwoFactorTurnOffResponseDto } from './twoFactorTurnOffResponseDto';

export type AuthControllerTurnOff2FA200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: TwoFactorTurnOffResponseDto;
  message?: string;
  meta?: AuthControllerTurnOff2FA200Meta;
};
