/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */

export interface AwsSnsPushDetailsDto {
  /** AWS 리전 (Region) */
  region?: string;
  /** AWS Platform Application ARN */
  platformApplicationArn?: string;
  /** AWS Access Key ID */
  accessKeyId?: string;
  /** AWS Secret Access Key */
  secretAccessKey?: string;
}
