/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateResourceRequestDto {
  /**
     * 영문 소문자, 숫자, 하이픈(-), 언더스코어(_)로 구성된 고유 리소스 코드
     * @maxLength 50
     */
  key: string;
  /** @maxLength 100 */
  label: string;
  /** @maxLength 255 */
  description?: string;
  actions: string[];
}
