/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { FaqsControllerGetFaqs200Meta } from './faqsControllerGetFaqs200Meta';
import type { GetFaqsResponseDto } from './getFaqsResponseDto';

export type FaqsControllerGetFaqs200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: GetFaqsResponseDto;
  message?: string;
  meta?: FaqsControllerGetFaqs200Meta;
};
