/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { InquiryConfigDto } from './inquiryConfigDto';
import type { MaintenanceConfigDto } from './maintenanceConfigDto';
import type { OperationConfigDto } from './operationConfigDto';
import type { SecurityConfigDto } from './securityConfigDto';

export interface GetAdminSystemConfigResponseDto {
  /** 운영 설정 (시간, 공휴일, 안내메시지) */
  operation: OperationConfigDto;
  /** 시스템 점검 설정 (임시점검, 정기점검) */
  maintenance: MaintenanceConfigDto;
  /** 계정 및 인증 보안 정책 */
  security: SecurityConfigDto;
  /** 1:1 문의 정책 및 알림 연동 */
  inquiry: InquiryConfigDto;
}
