/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { UserProfileResponse } from './userProfileResponse';

export interface ImpersonationTokenResponseDto {
  userId: string;
  user: UserProfileResponse;
  accessToken: string;
  refreshToken: string;
  tokenType: string;
}
