/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */

export type InquiriesControllerGetAdminInquiriesSortItem = typeof InquiriesControllerGetAdminInquiriesSortItem[keyof typeof InquiriesControllerGetAdminInquiriesSortItem];


export const InquiriesControllerGetAdminInquiriesSortItem = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  status: 'status',
  title: 'title',
} as const;
