/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { LogManagementControllerGetStats200Meta } from './logManagementControllerGetStats200Meta';
import type { LogStatsResponseDto } from './logStatsResponseDto';

export type LogManagementControllerGetStats200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: LogStatsResponseDto;
  message?: string;
  meta?: LogManagementControllerGetStats200Meta;
};
