/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */

export interface LunchBreakDto {
  /** 점심시간 활성화 여부 */
  enabled: boolean;
  /** 점심시간 시작 시각 (HH:mm) */
  start: string;
  /** 점심시간 종료 시각 (HH:mm) */
  end: string;
}
