/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 예약 점검 시작 일시 (ISO 8601, 미지정 시 즉시 점검)
 * @nullable
 */
export type MaintenanceWindowDtoScheduledStartAt = { [key: string]: unknown } | null;
