/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { MessageTemplatesControllerRenderPreview200Meta } from './messageTemplatesControllerRenderPreview200Meta';
import type { RenderPreviewResponseDto } from './renderPreviewResponseDto';

export type MessageTemplatesControllerRenderPreview200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: RenderPreviewResponseDto;
  message?: string;
  meta?: MessageTemplatesControllerRenderPreview200Meta;
};
