/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { MessageChannel } from './messageChannel';

export type MessageTemplatesControllerGetMessageTemplatesParams = {
channel?: MessageChannel;
locale?: string;
/**
 * 코드/이름/제목 검색
 */
search?: string;
};
