/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */

export interface NhnSmsDetailsDto {
  /** NHN Cloud SMS AppKey */
  appKey?: string;
  /** NHN Cloud SMS SecretKey */
  secretKey?: string;
  /** 사전 등록된 대표 발신번호 */
  senderPhone?: string;
}
