/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { GetNoticeFeedFiltersDto } from './getNoticeFeedFiltersDto';
import type { NoticesControllerGetNoticeFeedDirectionItem } from './noticesControllerGetNoticeFeedDirectionItem';
import type { NoticesControllerGetNoticeFeedSortItem } from './noticesControllerGetNoticeFeedSortItem';

export type NoticesControllerGetNoticeFeedParams = {
sort?: NoticesControllerGetNoticeFeedSortItem[];
direction?: NoticesControllerGetNoticeFeedDirectionItem[];
search?: string;
/**
 * @nullable
 */
cursor?: string | null;
/**
 * @maximum 100
 */
limit?: number;
filters?: GetNoticeFeedFiltersDto;
};
