/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { NoticesControllerGetAdminNoticesSortItem } from './noticesControllerGetAdminNoticesSortItem';
import type { SortDirection } from './sortDirection';

export type NoticesControllerGetAdminNoticesParams = {
sort?: NoticesControllerGetAdminNoticesSortItem[];
direction?: SortDirection[];
search?: string;
page?: number;
/**
 * @maximum 100
 */
limit?: number;
};
