/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { OnboardingControllerVerifyEmail200Meta } from './onboardingControllerVerifyEmail200Meta';
import type { VerifyEmailResponseDto } from './verifyEmailResponseDto';

export type OnboardingControllerVerifyEmail200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: VerifyEmailResponseDto;
  message?: string;
  meta?: OnboardingControllerVerifyEmail200Meta;
};
