/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { IssueEmailChallengeResponseDto } from './issueEmailChallengeResponseDto';
import type { OnboardingControllerIssueEmailChallenge200Meta } from './onboardingControllerIssueEmailChallenge200Meta';

export type OnboardingControllerIssueEmailChallenge200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: IssueEmailChallengeResponseDto;
  message?: string;
  meta?: OnboardingControllerIssueEmailChallenge200Meta;
};
