/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 실시간 상태 안내 문구
 * @nullable
 */
export type OperatingStatusDtoMessage = { [key: string]: unknown } | null;
