/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */

export interface OperatingMessagesDto {
  /** 점심시간 안내 문구 */
  lunch: string;
  /** 운영시간 외 안내 문구 */
  offHours: string;
  /** 휴일 안내 문구 */
  holiday: string;
  /** 시스템 점검 안내 문구 */
  maintenance: string;
}
