/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */

export interface RecurringMaintenanceDto {
  /** 정기 점검 활성화 여부 */
  enabled: boolean;
  /** 정기 점검 안내 문구 */
  message: string;
  /** 정기 점검 반복 요일 (0: 일, 1: 월 ... 6: 토) */
  daysOfWeek: number[];
  /** 정기 점검 시작 시각 (HH:mm) */
  startTime: string;
  /** 정기 점검 종료 시각 (HH:mm) */
  endTime: string;
}
