/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterRequest {
  email: string;
  /**
     * @minLength 10
     * @maxLength 24
     */
  password: string;
  confirmPassword: string;
  /**
     * @minLength 1
     * @maxLength 120
     */
  name: string;
}
