/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { LockoutConfigDto } from './lockoutConfigDto';
import type { PasswordPolicyDto } from './passwordPolicyDto';
import type { RegistrationConfigDto } from './registrationConfigDto';
import type { SessionConfigDto } from './sessionConfigDto';
import type { TwoFactorConfigDto } from './twoFactorConfigDto';
import type { VerificationConfigDto } from './verificationConfigDto';

export interface SecurityConfigDto {
  /** 신규 회원가입 정책 */
  registration: RegistrationConfigDto;
  /** 세션 및 접속 보안 정책 */
  session: SessionConfigDto;
  /** 로그인 실패 및 계정 잠금 정책 */
  lockout: LockoutConfigDto;
  /** 비밀번호 보안 정책 */
  password: PasswordPolicyDto;
  /** 2단계 인증(2FA) 정책 */
  twoFactor?: TwoFactorConfigDto;
  /** OAuth state 유효기간 (분) */
  oauthStateTtlMinutes: number;
  /** 인증 challenge 유효기간 정책 */
  verification: VerificationConfigDto;
}
