/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */

export interface SendEmailVerificationResponseDto {
  ok: boolean;
  /** 인증 코드 유효 시간 (초) */
  expiresIn: number;
}
