/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { SystemConfigControllerUpdateInquiry200Meta } from './systemConfigControllerUpdateInquiry200Meta';
import type { UpdateInquiryTabResponseDto } from './updateInquiryTabResponseDto';

export type SystemConfigControllerUpdateInquiry200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: UpdateInquiryTabResponseDto;
  message?: string;
  meta?: SystemConfigControllerUpdateInquiry200Meta;
};
