/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTermGroupResponse } from './createTermGroupResponse';
import type { TermsControllerCreateTermGroup201Meta } from './termsControllerCreateTermGroup201Meta';

export type TermsControllerCreateTermGroup201 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: CreateTermGroupResponse;
  message?: string;
  meta?: TermsControllerCreateTermGroup201Meta;
};
