/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminTermDto } from './adminTermDto';
import type { TermsControllerDeleteTerm200Meta } from './termsControllerDeleteTerm200Meta';

export type TermsControllerDeleteTerm200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: AdminTermDto;
  message?: string;
  meta?: TermsControllerDeleteTerm200Meta;
};
