/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { TermsControllerUpdateTermGroup200Meta } from './termsControllerUpdateTermGroup200Meta';
import type { UpdateTermGroupResponse } from './updateTermGroupResponse';

export type TermsControllerUpdateTermGroup200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: UpdateTermGroupResponse;
  message?: string;
  meta?: TermsControllerUpdateTermGroup200Meta;
};
