/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { OperatingHolidayItemDto } from './operatingHolidayItemDto';
import type { OperatingHoursUpdateDto } from './operatingHoursUpdateDto';
import type { OperatingMessagesDto } from './operatingMessagesDto';

export interface UpdateOperationsDto {
  hours?: OperatingHoursUpdateDto;
  holidays?: OperatingHolidayItemDto[];
  messages?: OperatingMessagesDto;
}
