/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { OperatingHolidayItemDto } from './operatingHolidayItemDto';
import type { OperatingHoursUpdateDto } from './operatingHoursUpdateDto';

export interface UpdateOperationsTabRequestDto {
  /** 운영시간 설정 */
  hours: OperatingHoursUpdateDto;
  /** 공휴일 및 특별 휴무일 목록 */
  holidays: OperatingHolidayItemDto[];
}
