/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthPolicyValueDto } from './authPolicyValueDto';
import type { InquiryPolicyValueDto } from './inquiryPolicyValueDto';
import type { SlackNotificationValueDto } from './slackNotificationValueDto';

export interface UpdateSecurityTabRequestDto {
  authPolicy: AuthPolicyValueDto;
  slackNotification: SlackNotificationValueDto;
  inquiryPolicy: InquiryPolicyValueDto;
}
