/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 설정 설명
 * @nullable
 */
export type UpdateSystemConfigResponseDescription = { [key: string]: unknown } | null;
