/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { UserDetailDto } from './userDetailDto';
import type { UsersControllerRestoreUser200Meta } from './usersControllerRestoreUser200Meta';

export type UsersControllerRestoreUser200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: UserDetailDto;
  message?: string;
  meta?: UsersControllerRestoreUser200Meta;
};
