/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteUserResponse } from './deleteUserResponse';
import type { UsersControllerDeleteUser200Meta } from './usersControllerDeleteUser200Meta';

export type UsersControllerDeleteUser200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: DeleteUserResponse;
  message?: string;
  meta?: UsersControllerDeleteUser200Meta;
};
