/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { UserOverviewDto } from './userOverviewDto';
import type { UsersControllerGetUserOverview200Meta } from './usersControllerGetUserOverview200Meta';

export type UsersControllerGetUserOverview200 = {
  success: boolean;
  statusCode: number;
  path: string;
  requestId: string;
  timestamp: string;
  data: UserOverviewDto;
  message?: string;
  meta?: UsersControllerGetUserOverview200Meta;
};
