/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import type { VerifyIdentityPhoneChangeResponseDtoGender } from './verifyIdentityPhoneChangeResponseDtoGender';

export interface VerifyIdentityPhoneChangeResponseDto {
  ok: boolean;
  name: string;
  phoneNumber: string;
  phoneNumberVerified: boolean;
  /** @nullable */
  birthDate?: string | null;
  /** @nullable */
  gender?: VerifyIdentityPhoneChangeResponseDtoGender;
}
