/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Nest Starter Kit
 * NestJS + MikroORM Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  UsersControllerGetUserById200,
  UsersControllerGetUserOverview200,
  UsersControllerGetUsers200,
  UsersControllerGetUsersParams,
  UsersControllerImpersonateUser200
} from '../../model';

import { axios } from '../../../../core/config/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const usersControllerGetUsers = (
    params?: UsersControllerGetUsersParams,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<UsersControllerGetUsers200>(
      {url: `/api/v1/users`, method: 'GET',
        params, signal
    },
      options);
    }




export const getUsersControllerGetUsersQueryKey = (params?: UsersControllerGetUsersParams,) => {
    return [
    `/api/v1/users`, ...(params ? [params] : [])
    ] as const;
    }


export const getUsersControllerGetUsersQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetUsers>>, TError = unknown>(params?: UsersControllerGetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUsers>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetUsersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetUsers>>> = ({ signal }) => usersControllerGetUsers(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerGetUsersQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetUsers>>>
export type UsersControllerGetUsersQueryError = unknown


export function useUsersControllerGetUsers<TData = Awaited<ReturnType<typeof usersControllerGetUsers>>, TError = unknown>(
 params: undefined |  UsersControllerGetUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUsers>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetUsers<TData = Awaited<ReturnType<typeof usersControllerGetUsers>>, TError = unknown>(
 params?: UsersControllerGetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUsers>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetUsers<TData = Awaited<ReturnType<typeof usersControllerGetUsers>>, TError = unknown>(
 params?: UsersControllerGetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUsers>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersControllerGetUsers<TData = Awaited<ReturnType<typeof usersControllerGetUsers>>, TError = unknown>(
 params?: UsersControllerGetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUsers>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerGetUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const usersControllerGetUserOverview = (

 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<UsersControllerGetUserOverview200>(
      {url: `/api/v1/users/overview`, method: 'GET', signal
    },
      options);
    }




export const getUsersControllerGetUserOverviewQueryKey = () => {
    return [
    `/api/v1/users/overview`
    ] as const;
    }


export const getUsersControllerGetUserOverviewQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetUserOverview>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserOverview>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetUserOverviewQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetUserOverview>>> = ({ signal }) => usersControllerGetUserOverview(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserOverview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerGetUserOverviewQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetUserOverview>>>
export type UsersControllerGetUserOverviewQueryError = unknown


export function useUsersControllerGetUserOverview<TData = Awaited<ReturnType<typeof usersControllerGetUserOverview>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserOverview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUserOverview>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUserOverview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetUserOverview<TData = Awaited<ReturnType<typeof usersControllerGetUserOverview>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserOverview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUserOverview>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUserOverview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetUserOverview<TData = Awaited<ReturnType<typeof usersControllerGetUserOverview>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserOverview>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersControllerGetUserOverview<TData = Awaited<ReturnType<typeof usersControllerGetUserOverview>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserOverview>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerGetUserOverviewQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const usersControllerGetUserById = (
    id: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<UsersControllerGetUserById200>(
      {url: `/api/v1/users/${id}`, method: 'GET', signal
    },
      options);
    }




export const getUsersControllerGetUserByIdQueryKey = (id: string,) => {
    return [
    `/api/v1/users/${id}`
    ] as const;
    }


export const getUsersControllerGetUserByIdQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetUserById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserById>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetUserByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetUserById>>> = ({ signal }) => usersControllerGetUserById(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerGetUserByIdQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetUserById>>>
export type UsersControllerGetUserByIdQueryError = unknown


export function useUsersControllerGetUserById<TData = Awaited<ReturnType<typeof usersControllerGetUserById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUserById>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUserById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetUserById<TData = Awaited<ReturnType<typeof usersControllerGetUserById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUserById>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUserById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetUserById<TData = Awaited<ReturnType<typeof usersControllerGetUserById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserById>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersControllerGetUserById<TData = Awaited<ReturnType<typeof usersControllerGetUserById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserById>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerGetUserByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const usersControllerImpersonateUser = (
    id: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {


      return axios<UsersControllerImpersonateUser200>(
      {url: `/api/v1/users/${id}/impersonate`, method: 'POST', signal
    },
      options);
    }




export const getUsersControllerImpersonateUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerImpersonateUser>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerImpersonateUser>>, TError,{id: string}, TContext> => {

const mutationKey = ['usersControllerImpersonateUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerImpersonateUser>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  usersControllerImpersonateUser(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerImpersonateUserMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerImpersonateUser>>>

    export type UsersControllerImpersonateUserMutationError = unknown

    export const useUsersControllerImpersonateUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerImpersonateUser>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerImpersonateUser>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getUsersControllerImpersonateUserMutationOptions(options), queryClient);
    }
